# --- !Ups
INSERT INTO colour (name, hex) values ('000000', 'Black');
INSERT INTO colour (name, hex) values ('000080', 'Navy Blue');
INSERT INTO colour (name, hex) values ('0000C8', 'Dark Blue');
INSERT INTO colour (name, hex) values ('0000FF', 'Blue');
INSERT INTO colour (name, hex) values ('000741', 'Stratos');
INSERT INTO colour (name, hex) values ('001B1C', 'Swamp');
INSERT INTO colour (name, hex) values ('002387', 'Resolution Blue');
INSERT INTO colour (name, hex) values ('002900', 'Deep Fir');
INSERT INTO colour (name, hex) values ('002E20', 'Burnham');
INSERT INTO colour (name, hex) values ('002FA7', 'International Klein Blue');
INSERT INTO colour (name, hex) values ('003153', 'Prussian Blue');
INSERT INTO colour (name, hex) values ('003366', 'Midnight Blue');
INSERT INTO colour (name, hex) values ('003399', 'Smalt');
INSERT INTO colour (name, hex) values ('003532', 'Deep Teal');
INSERT INTO colour (name, hex) values ('003E40', 'Cyprus');
INSERT INTO colour (name, hex) values ('004620', 'Kaitoke Green');
INSERT INTO colour (name, hex) values ('0047AB', 'Cobalt');
INSERT INTO colour (name, hex) values ('004816', 'Crusoe');
INSERT INTO colour (name, hex) values ('004950', 'Sherpa Blue');
INSERT INTO colour (name, hex) values ('0056A7', 'Endeavour');
INSERT INTO colour (name, hex) values ('00581A', 'Camarone');
INSERT INTO colour (name, hex) values ('0066CC', 'Science Blue');
INSERT INTO colour (name, hex) values ('0066FF', 'Blue Ribbon');
INSERT INTO colour (name, hex) values ('00755E', 'Tropical Rain Forest');
INSERT INTO colour (name, hex) values ('0076A3', 'Allports');
INSERT INTO colour (name, hex) values ('007BA7', 'Deep Cerulean');
INSERT INTO colour (name, hex) values ('007EC7', 'Lochmara');
INSERT INTO colour (name, hex) values ('007FFF', 'Azure Radiance');
INSERT INTO colour (name, hex) values ('008080', 'Teal');
INSERT INTO colour (name, hex) values ('0095B6', 'Bondi Blue');
INSERT INTO colour (name, hex) values ('009DC4', 'Pacific Blue');
INSERT INTO colour (name, hex) values ('00A693', 'Persian Green');
INSERT INTO colour (name, hex) values ('00A86B', 'Jade');
INSERT INTO colour (name, hex) values ('00CC99', 'Caribbean Green');
INSERT INTO colour (name, hex) values ('00CCCC', 'Robin''s Egg Blue');
INSERT INTO colour (name, hex) values ('00FF00', 'Green');
INSERT INTO colour (name, hex) values ('00FF7F', 'Spring Green');
INSERT INTO colour (name, hex) values ('00FFFF', 'Cyan / Aqua');
INSERT INTO colour (name, hex) values ('010D1A', 'Blue Charcoal');
INSERT INTO colour (name, hex) values ('011635', 'Midnight');
INSERT INTO colour (name, hex) values ('011D13', 'Holly');
INSERT INTO colour (name, hex) values ('012731', 'Daintree');
INSERT INTO colour (name, hex) values ('01361C', 'Cardin Green');
INSERT INTO colour (name, hex) values ('01371A', 'County Green');
INSERT INTO colour (name, hex) values ('013E62', 'Astronaut Blue');
INSERT INTO colour (name, hex) values ('013F6A', 'Regal Blue');
INSERT INTO colour (name, hex) values ('014B43', 'Aqua Deep');
INSERT INTO colour (name, hex) values ('015E85', 'Orient');
INSERT INTO colour (name, hex) values ('016162', 'Blue Stone');
INSERT INTO colour (name, hex) values ('016D39', 'Fun Green');
INSERT INTO colour (name, hex) values ('01796F', 'Pine Green');
INSERT INTO colour (name, hex) values ('017987', 'Blue Lagoon');
INSERT INTO colour (name, hex) values ('01826B', 'Deep Sea');
INSERT INTO colour (name, hex) values ('01A368', 'Green Haze');
INSERT INTO colour (name, hex) values ('022D15', 'English Holly');
INSERT INTO colour (name, hex) values ('02402C', 'Sherwood Green');
INSERT INTO colour (name, hex) values ('02478E', 'Congress Blue');
INSERT INTO colour (name, hex) values ('024E46', 'Evening Sea');
INSERT INTO colour (name, hex) values ('026395', 'Bahama Blue');
INSERT INTO colour (name, hex) values ('02866F', 'Observatory');
INSERT INTO colour (name, hex) values ('02A4D3', 'Cerulean');
INSERT INTO colour (name, hex) values ('03163C', 'Tangaroa');
INSERT INTO colour (name, hex) values ('032B52', 'Green Vogue');
INSERT INTO colour (name, hex) values ('036A6E', 'Mosque');
INSERT INTO colour (name, hex) values ('041004', 'Midnight Moss');
INSERT INTO colour (name, hex) values ('041322', 'Black Pearl');
INSERT INTO colour (name, hex) values ('042E4C', 'Blue Whale');
INSERT INTO colour (name, hex) values ('044022', 'Zuccini');
INSERT INTO colour (name, hex) values ('044259', 'Teal Blue');
INSERT INTO colour (name, hex) values ('051040', 'Deep Cove');
INSERT INTO colour (name, hex) values ('051657', 'Gulf Blue');
INSERT INTO colour (name, hex) values ('055989', 'Venice Blue');
INSERT INTO colour (name, hex) values ('056F57', 'Watercourse');
INSERT INTO colour (name, hex) values ('062A78', 'Catalina Blue');
INSERT INTO colour (name, hex) values ('063537', 'Tiber');
INSERT INTO colour (name, hex) values ('069B81', 'Gossamer');
INSERT INTO colour (name, hex) values ('06A189', 'Niagara');
INSERT INTO colour (name, hex) values ('073A50', 'Tarawera');
INSERT INTO colour (name, hex) values ('080110', 'Jaguar');
INSERT INTO colour (name, hex) values ('081910', 'Black Bean');
INSERT INTO colour (name, hex) values ('082567', 'Deep Sapphire');
INSERT INTO colour (name, hex) values ('088370', 'Elf Green');
INSERT INTO colour (name, hex) values ('08E8DE', 'Bright Turquoise');
INSERT INTO colour (name, hex) values ('092256', 'Downriver');
INSERT INTO colour (name, hex) values ('09230F', 'Palm Green');
INSERT INTO colour (name, hex) values ('09255D', 'Madison');
INSERT INTO colour (name, hex) values ('093624', 'Bottle Green');
INSERT INTO colour (name, hex) values ('095859', 'Deep Sea Green');
INSERT INTO colour (name, hex) values ('097F4B', 'Salem');
INSERT INTO colour (name, hex) values ('0A001C', 'Black Russian');
INSERT INTO colour (name, hex) values ('0A480D', 'Dark Fern');
INSERT INTO colour (name, hex) values ('0A6906', 'Japanese Laurel');
INSERT INTO colour (name, hex) values ('0A6F75', 'Atoll');
INSERT INTO colour (name, hex) values ('0B0B0B', 'Cod Gray');
INSERT INTO colour (name, hex) values ('0B0F08', 'Marshland');
INSERT INTO colour (name, hex) values ('0B1107', 'Gordons Green');
INSERT INTO colour (name, hex) values ('0B1304', 'Black Forest');
INSERT INTO colour (name, hex) values ('0B6207', 'San Felix');
INSERT INTO colour (name, hex) values ('0BDA51', 'Malachite');
INSERT INTO colour (name, hex) values ('0C0B1D', 'Ebony');
INSERT INTO colour (name, hex) values ('0C0D0F', 'Woodsmoke');
INSERT INTO colour (name, hex) values ('0C1911', 'Racing Green');
INSERT INTO colour (name, hex) values ('0C7A79', 'Surfie Green');
INSERT INTO colour (name, hex) values ('0C8990', 'Blue Chill');
INSERT INTO colour (name, hex) values ('0D0332', 'Black Rock');
INSERT INTO colour (name, hex) values ('0D1117', 'Bunker');
INSERT INTO colour (name, hex) values ('0D1C19', 'Aztec');
INSERT INTO colour (name, hex) values ('0D2E1C', 'Bush');
INSERT INTO colour (name, hex) values ('0E0E18', 'Cinder');
INSERT INTO colour (name, hex) values ('0E2A30', 'Firefly');
INSERT INTO colour (name, hex) values ('0F2D9E', 'Torea Bay');
INSERT INTO colour (name, hex) values ('10121D', 'Vulcan');
INSERT INTO colour (name, hex) values ('101405', 'Green Waterloo');
INSERT INTO colour (name, hex) values ('105852', 'Eden');
INSERT INTO colour (name, hex) values ('110C6C', 'Arapawa');
INSERT INTO colour (name, hex) values ('120A8F', 'Ultramarine');
INSERT INTO colour (name, hex) values ('123447', 'Elephant');
INSERT INTO colour (name, hex) values ('126B40', 'Jewel');
INSERT INTO colour (name, hex) values ('130000', 'Diesel');
INSERT INTO colour (name, hex) values ('130A06', 'Asphalt');
INSERT INTO colour (name, hex) values ('13264D', 'Blue Zodiac');
INSERT INTO colour (name, hex) values ('134F19', 'Parsley');
INSERT INTO colour (name, hex) values ('140600', 'Nero');
INSERT INTO colour (name, hex) values ('1450AA', 'Tory Blue');
INSERT INTO colour (name, hex) values ('151F4C', 'Bunting');
INSERT INTO colour (name, hex) values ('1560BD', 'Denim');
INSERT INTO colour (name, hex) values ('15736B', 'Genoa');
INSERT INTO colour (name, hex) values ('161928', 'Mirage');
INSERT INTO colour (name, hex) values ('161D10', 'Hunter Green');
INSERT INTO colour (name, hex) values ('162A40', 'Big Stone');
INSERT INTO colour (name, hex) values ('163222', 'Celtic');
INSERT INTO colour (name, hex) values ('16322C', 'Timber Green');
INSERT INTO colour (name, hex) values ('163531', 'Gable Green');
INSERT INTO colour (name, hex) values ('171F04', 'Pine Tree');
INSERT INTO colour (name, hex) values ('175579', 'Chathams Blue');
INSERT INTO colour (name, hex) values ('182D09', 'Deep Forest Green');
INSERT INTO colour (name, hex) values ('18587A', 'Blumine');
INSERT INTO colour (name, hex) values ('19330E', 'Palm Leaf');
INSERT INTO colour (name, hex) values ('193751', 'Nile Blue');
INSERT INTO colour (name, hex) values ('1959A8', 'Fun Blue');
INSERT INTO colour (name, hex) values ('1A1A68', 'Lucky Point');
INSERT INTO colour (name, hex) values ('1AB385', 'Mountain Meadow');
INSERT INTO colour (name, hex) values ('1B0245', 'Tolopea');
INSERT INTO colour (name, hex) values ('1B1035', 'Haiti');
INSERT INTO colour (name, hex) values ('1B127B', 'Deep Koamaru');
INSERT INTO colour (name, hex) values ('1B1404', 'Acadia');
INSERT INTO colour (name, hex) values ('1B2F11', 'Seaweed');
INSERT INTO colour (name, hex) values ('1B3162', 'Biscay');
INSERT INTO colour (name, hex) values ('1B659D', 'Matisse');
INSERT INTO colour (name, hex) values ('1C1208', 'Crowshead');
INSERT INTO colour (name, hex) values ('1C1E13', 'Rangoon Green');
INSERT INTO colour (name, hex) values ('1C39BB', 'Persian Blue');
INSERT INTO colour (name, hex) values ('1C402E', 'Everglade');
INSERT INTO colour (name, hex) values ('1C7C7D', 'Elm');
INSERT INTO colour (name, hex) values ('1D6142', 'Green Pea');
INSERT INTO colour (name, hex) values ('1E0F04', 'Creole');
INSERT INTO colour (name, hex) values ('1E1609', 'Karaka');
INSERT INTO colour (name, hex) values ('1E1708', 'El Paso');
INSERT INTO colour (name, hex) values ('1E385B', 'Cello');
INSERT INTO colour (name, hex) values ('1E433C', 'Te Papa Green');
INSERT INTO colour (name, hex) values ('1E90FF', 'Dodger Blue');
INSERT INTO colour (name, hex) values ('1E9AB0', 'Eastern Blue');
INSERT INTO colour (name, hex) values ('1F120F', 'Night Rider');
INSERT INTO colour (name, hex) values ('1FC2C2', 'Java');
INSERT INTO colour (name, hex) values ('20208D', 'Jacksons Purple');
INSERT INTO colour (name, hex) values ('202E54', 'Cloud Burst');
INSERT INTO colour (name, hex) values ('204852', 'Blue Dianne');
INSERT INTO colour (name, hex) values ('211A0E', 'Eternity');
INSERT INTO colour (name, hex) values ('220878', 'Deep Blue');
INSERT INTO colour (name, hex) values ('228B22', 'Forest Green');
INSERT INTO colour (name, hex) values ('233418', 'Mallard');
INSERT INTO colour (name, hex) values ('240A40', 'Violet');
INSERT INTO colour (name, hex) values ('240C02', 'Kilamanjaro');
INSERT INTO colour (name, hex) values ('242A1D', 'Log Cabin');
INSERT INTO colour (name, hex) values ('242E16', 'Black Olive');
INSERT INTO colour (name, hex) values ('24500F', 'Green House');
INSERT INTO colour (name, hex) values ('251607', 'Graphite');
INSERT INTO colour (name, hex) values ('251706', 'Cannon Black');
INSERT INTO colour (name, hex) values ('251F4F', 'Port Gore');
INSERT INTO colour (name, hex) values ('25272C', 'Shark');
INSERT INTO colour (name, hex) values ('25311C', 'Green Kelp');
INSERT INTO colour (name, hex) values ('2596D1', 'Curious Blue');
INSERT INTO colour (name, hex) values ('260368', 'Paua');
INSERT INTO colour (name, hex) values ('26056A', 'Paris M');
INSERT INTO colour (name, hex) values ('261105', 'Wood Bark');
INSERT INTO colour (name, hex) values ('261414', 'Gondola');
INSERT INTO colour (name, hex) values ('262335', 'Steel Gray');
INSERT INTO colour (name, hex) values ('26283B', 'Ebony Clay');
INSERT INTO colour (name, hex) values ('273A81', 'Bay of Many');
INSERT INTO colour (name, hex) values ('27504B', 'Plantation');
INSERT INTO colour (name, hex) values ('278A5B', 'Eucalyptus');
INSERT INTO colour (name, hex) values ('281E15', 'Oil');
INSERT INTO colour (name, hex) values ('283A77', 'Astronaut');
INSERT INTO colour (name, hex) values ('286ACD', 'Mariner');
INSERT INTO colour (name, hex) values ('290C5E', 'Violent Violet');
INSERT INTO colour (name, hex) values ('292130', 'Bastille');
INSERT INTO colour (name, hex) values ('292319', 'Zeus');
INSERT INTO colour (name, hex) values ('292937', 'Charade');
INSERT INTO colour (name, hex) values ('297B9A', 'Jelly Bean');
INSERT INTO colour (name, hex) values ('29AB87', 'Jungle Green');
INSERT INTO colour (name, hex) values ('2A0359', 'Cherry Pie');
INSERT INTO colour (name, hex) values ('2A140E', 'Coffee Bean');
INSERT INTO colour (name, hex) values ('2A2630', 'Baltic Sea');
INSERT INTO colour (name, hex) values ('2A380B', 'Turtle Green');
INSERT INTO colour (name, hex) values ('2A52BE', 'Cerulean Blue');
INSERT INTO colour (name, hex) values ('2B0202', 'Sepia Black');
INSERT INTO colour (name, hex) values ('2B194F', 'Valhalla');
INSERT INTO colour (name, hex) values ('2B3228', 'Heavy Metal');
INSERT INTO colour (name, hex) values ('2C0E8C', 'Blue Gem');
INSERT INTO colour (name, hex) values ('2C1632', 'Revolver');
INSERT INTO colour (name, hex) values ('2C2133', 'Bleached Cedar');
INSERT INTO colour (name, hex) values ('2C8C84', 'Lochinvar');
INSERT INTO colour (name, hex) values ('2D2510', 'Mikado');
INSERT INTO colour (name, hex) values ('2D383A', 'Outer Space');
INSERT INTO colour (name, hex) values ('2D569B', 'St Tropaz');
INSERT INTO colour (name, hex) values ('2E0329', 'Jacaranda');
INSERT INTO colour (name, hex) values ('2E1905', 'Jacko Bean');
INSERT INTO colour (name, hex) values ('2E3222', 'Rangitoto');
INSERT INTO colour (name, hex) values ('2E3F62', 'Rhino');
INSERT INTO colour (name, hex) values ('2E8B57', 'Sea Green');
INSERT INTO colour (name, hex) values ('2EBFD4', 'Scooter');
INSERT INTO colour (name, hex) values ('2F270E', 'Onion');
INSERT INTO colour (name, hex) values ('2F3CB3', 'Governor Bay');
INSERT INTO colour (name, hex) values ('2F519E', 'Sapphire');
INSERT INTO colour (name, hex) values ('2F5A57', 'Spectra');
INSERT INTO colour (name, hex) values ('2F6168', 'Casal');
INSERT INTO colour (name, hex) values ('300529', 'Melanzane');
INSERT INTO colour (name, hex) values ('301F1E', 'Cocoa Brown');
INSERT INTO colour (name, hex) values ('302A0F', 'Woodrush');
INSERT INTO colour (name, hex) values ('304B6A', 'San Juan');
INSERT INTO colour (name, hex) values ('30D5C8', 'Turquoise');
INSERT INTO colour (name, hex) values ('311C17', 'Eclipse');
INSERT INTO colour (name, hex) values ('314459', 'Pickled Bluewood');
INSERT INTO colour (name, hex) values ('315BA1', 'Azure');
INSERT INTO colour (name, hex) values ('31728D', 'Calypso');
INSERT INTO colour (name, hex) values ('317D82', 'Paradiso');
INSERT INTO colour (name, hex) values ('32127A', 'Persian Indigo');
INSERT INTO colour (name, hex) values ('32293A', 'Blackcurrant');
INSERT INTO colour (name, hex) values ('323232', 'Mine Shaft');
INSERT INTO colour (name, hex) values ('325D52', 'Stromboli');
INSERT INTO colour (name, hex) values ('327C14', 'Bilbao');
INSERT INTO colour (name, hex) values ('327DA0', 'Astral');
INSERT INTO colour (name, hex) values ('33036B', 'Christalle');
INSERT INTO colour (name, hex) values ('33292F', 'Thunder');
INSERT INTO colour (name, hex) values ('33CC99', 'Shamrock');
INSERT INTO colour (name, hex) values ('341515', 'Tamarind');
INSERT INTO colour (name, hex) values ('350036', 'Mardi Gras');
INSERT INTO colour (name, hex) values ('350E42', 'Valentino');
INSERT INTO colour (name, hex) values ('350E57', 'Jagger');
INSERT INTO colour (name, hex) values ('353542', 'Tuna');
INSERT INTO colour (name, hex) values ('354E8C', 'Chambray');
INSERT INTO colour (name, hex) values ('363050', 'Martinique');
INSERT INTO colour (name, hex) values ('363534', 'Tuatara');
INSERT INTO colour (name, hex) values ('363C0D', 'Waiouru');
INSERT INTO colour (name, hex) values ('36747D', 'Ming');
INSERT INTO colour (name, hex) values ('368716', 'La Palma');
INSERT INTO colour (name, hex) values ('370202', 'Chocolate');
INSERT INTO colour (name, hex) values ('371D09', 'Clinker');
INSERT INTO colour (name, hex) values ('37290E', 'Brown Tumbleweed');
INSERT INTO colour (name, hex) values ('373021', 'Birch');
INSERT INTO colour (name, hex) values ('377475', 'Oracle');
INSERT INTO colour (name, hex) values ('380474', 'Blue Diamond');
INSERT INTO colour (name, hex) values ('381A51', 'Grape');
INSERT INTO colour (name, hex) values ('383533', 'Dune');
INSERT INTO colour (name, hex) values ('384555', 'Oxford Blue');
INSERT INTO colour (name, hex) values ('384910', 'Clover');
INSERT INTO colour (name, hex) values ('394851', 'Limed Spruce');
INSERT INTO colour (name, hex) values ('396413', 'Dell');
INSERT INTO colour (name, hex) values ('3A0020', 'Toledo');
INSERT INTO colour (name, hex) values ('3A2010', 'Sambuca');
INSERT INTO colour (name, hex) values ('3A2A6A', 'Jacarta');
INSERT INTO colour (name, hex) values ('3A686C', 'William');
INSERT INTO colour (name, hex) values ('3A6A47', 'Killarney');
INSERT INTO colour (name, hex) values ('3AB09E', 'Keppel');
INSERT INTO colour (name, hex) values ('3B000B', 'Temptress');
INSERT INTO colour (name, hex) values ('3B0910', 'Aubergine');
INSERT INTO colour (name, hex) values ('3B1F1F', 'Jon');
INSERT INTO colour (name, hex) values ('3B2820', 'Treehouse');
INSERT INTO colour (name, hex) values ('3B7A57', 'Amazon');
INSERT INTO colour (name, hex) values ('3B91B4', 'Boston Blue');
INSERT INTO colour (name, hex) values ('3C0878', 'Windsor');
INSERT INTO colour (name, hex) values ('3C1206', 'Rebel');
INSERT INTO colour (name, hex) values ('3C1F76', 'Meteorite');
INSERT INTO colour (name, hex) values ('3C2005', 'Dark Ebony');
INSERT INTO colour (name, hex) values ('3C3910', 'Camouflage');
INSERT INTO colour (name, hex) values ('3C4151', 'Bright Gray');
INSERT INTO colour (name, hex) values ('3C4443', 'Cape Cod');
INSERT INTO colour (name, hex) values ('3C493A', 'Lunar Green');
INSERT INTO colour (name, hex) values ('3D0C02', 'Bean  ');
INSERT INTO colour (name, hex) values ('3D2B1F', 'Bistre');
INSERT INTO colour (name, hex) values ('3D7D52', 'Goblin');
INSERT INTO colour (name, hex) values ('3E0480', 'Kingfisher Daisy');
INSERT INTO colour (name, hex) values ('3E1C14', 'Cedar');
INSERT INTO colour (name, hex) values ('3E2B23', 'English Walnut');
INSERT INTO colour (name, hex) values ('3E2C1C', 'Black Marlin');
INSERT INTO colour (name, hex) values ('3E3A44', 'Ship Gray');
INSERT INTO colour (name, hex) values ('3EABBF', 'Pelorous');
INSERT INTO colour (name, hex) values ('3F2109', 'Bronze');
INSERT INTO colour (name, hex) values ('3F2500', 'Cola');
INSERT INTO colour (name, hex) values ('3F3002', 'Madras');
INSERT INTO colour (name, hex) values ('3F307F', 'Minsk');
INSERT INTO colour (name, hex) values ('3F4C3A', 'Cabbage Pont');
INSERT INTO colour (name, hex) values ('3F583B', 'Tom Thumb');
INSERT INTO colour (name, hex) values ('3F5D53', 'Mineral Green');
INSERT INTO colour (name, hex) values ('3FC1AA', 'Puerto Rico');
INSERT INTO colour (name, hex) values ('3FFF00', 'Harlequin');
INSERT INTO colour (name, hex) values ('401801', 'Brown Pod');
INSERT INTO colour (name, hex) values ('40291D', 'Cork');
INSERT INTO colour (name, hex) values ('403B38', 'Masala');
INSERT INTO colour (name, hex) values ('403D19', 'Thatch Green');
INSERT INTO colour (name, hex) values ('405169', 'Fiord');
INSERT INTO colour (name, hex) values ('40826D', 'Viridian');
INSERT INTO colour (name, hex) values ('40A860', 'Chateau Green');
INSERT INTO colour (name, hex) values ('410056', 'Ripe Plum');
INSERT INTO colour (name, hex) values ('411F10', 'Paco');
INSERT INTO colour (name, hex) values ('412010', 'Deep Oak');
INSERT INTO colour (name, hex) values ('413C37', 'Merlin');
INSERT INTO colour (name, hex) values ('414257', 'Gun Powder');
INSERT INTO colour (name, hex) values ('414C7D', 'East Bay');
INSERT INTO colour (name, hex) values ('4169E1', 'Royal Blue');
INSERT INTO colour (name, hex) values ('41AA78', 'Ocean Green');
INSERT INTO colour (name, hex) values ('420303', 'Burnt Maroon');
INSERT INTO colour (name, hex) values ('423921', 'Lisbon Brown');
INSERT INTO colour (name, hex) values ('427977', 'Faded Jade');
INSERT INTO colour (name, hex) values ('431560', 'Scarlet Gum');
INSERT INTO colour (name, hex) values ('433120', 'Iroko');
INSERT INTO colour (name, hex) values ('433E37', 'Armadillo');
INSERT INTO colour (name, hex) values ('434C59', 'River Bed');
INSERT INTO colour (name, hex) values ('436A0D', 'Green Leaf');
INSERT INTO colour (name, hex) values ('44012D', 'Barossa');
INSERT INTO colour (name, hex) values ('441D00', 'Morocco Brown');
INSERT INTO colour (name, hex) values ('444954', 'Mako');
INSERT INTO colour (name, hex) values ('454936', 'Kelp');
INSERT INTO colour (name, hex) values ('456CAC', 'San Marino');
INSERT INTO colour (name, hex) values ('45B1E8', 'Picton Blue');
INSERT INTO colour (name, hex) values ('460B41', 'Loulou');
INSERT INTO colour (name, hex) values ('462425', 'Crater Brown');
INSERT INTO colour (name, hex) values ('465945', 'Gray Asparagus');
INSERT INTO colour (name, hex) values ('4682B4', 'Steel Blue');
INSERT INTO colour (name, hex) values ('480404', 'Rustic Red');
INSERT INTO colour (name, hex) values ('480607', 'Bulgarian Rose');
INSERT INTO colour (name, hex) values ('480656', 'Clairvoyant');
INSERT INTO colour (name, hex) values ('481C1C', 'Cocoa Bean');
INSERT INTO colour (name, hex) values ('483131', 'Woody Brown');
INSERT INTO colour (name, hex) values ('483C32', 'Taupe');
INSERT INTO colour (name, hex) values ('49170C', 'Van Cleef');
INSERT INTO colour (name, hex) values ('492615', 'Brown Derby');
INSERT INTO colour (name, hex) values ('49371B', 'Metallic Bronze');
INSERT INTO colour (name, hex) values ('495400', 'Verdun Green');
INSERT INTO colour (name, hex) values ('496679', 'Blue Bayoux');
INSERT INTO colour (name, hex) values ('497183', 'Bismark');
INSERT INTO colour (name, hex) values ('4A2A04', 'Bracken');
INSERT INTO colour (name, hex) values ('4A3004', 'Deep Bronze');
INSERT INTO colour (name, hex) values ('4A3C30', 'Mondo');
INSERT INTO colour (name, hex) values ('4A4244', 'Tundora');
INSERT INTO colour (name, hex) values ('4A444B', 'Gravel');
INSERT INTO colour (name, hex) values ('4A4E5A', 'Trout');
INSERT INTO colour (name, hex) values ('4B0082', 'Pigment Indigo');
INSERT INTO colour (name, hex) values ('4B5D52', 'Nandor');
INSERT INTO colour (name, hex) values ('4C3024', 'Saddle');
INSERT INTO colour (name, hex) values ('4C4F56', 'Abbey');
INSERT INTO colour (name, hex) values ('4D0135', 'Blackberry');
INSERT INTO colour (name, hex) values ('4D0A18', 'Cab Sav');
INSERT INTO colour (name, hex) values ('4D1E01', 'Indian Tan');
INSERT INTO colour (name, hex) values ('4D282D', 'Cowboy');
INSERT INTO colour (name, hex) values ('4D282E', 'Livid Brown');
INSERT INTO colour (name, hex) values ('4D3833', 'Rock');
INSERT INTO colour (name, hex) values ('4D3D14', 'Punga');
INSERT INTO colour (name, hex) values ('4D400F', 'Bronzetone');
INSERT INTO colour (name, hex) values ('4D5328', 'Woodland');
INSERT INTO colour (name, hex) values ('4E0606', 'Mahogany');
INSERT INTO colour (name, hex) values ('4E2A5A', 'Bossanova');
INSERT INTO colour (name, hex) values ('4E3B41', 'Matterhorn');
INSERT INTO colour (name, hex) values ('4E420C', 'Bronze Olive');
INSERT INTO colour (name, hex) values ('4E4562', 'Mulled Wine');
INSERT INTO colour (name, hex) values ('4E6649', 'Axolotl');
INSERT INTO colour (name, hex) values ('4E7F9E', 'Wedgewood');
INSERT INTO colour (name, hex) values ('4EABD1', 'Shakespeare');
INSERT INTO colour (name, hex) values ('4F1C70', 'Honey Flower');
INSERT INTO colour (name, hex) values ('4F2398', 'Daisy Bush');
INSERT INTO colour (name, hex) values ('4F69C6', 'Indigo');
INSERT INTO colour (name, hex) values ('4F7942', 'Fern Green');
INSERT INTO colour (name, hex) values ('4F9D5D', 'Fruit Salad');
INSERT INTO colour (name, hex) values ('4FA83D', 'Apple');
INSERT INTO colour (name, hex) values ('504351', 'Mortar');
INSERT INTO colour (name, hex) values ('507096', 'Kashmir Blue');
INSERT INTO colour (name, hex) values ('507672', 'Cutty Sark');
INSERT INTO colour (name, hex) values ('50C878', 'Emerald');
INSERT INTO colour (name, hex) values ('514649', 'Emperor');
INSERT INTO colour (name, hex) values ('516E3D', 'Chalet Green');
INSERT INTO colour (name, hex) values ('517C66', 'Como');
INSERT INTO colour (name, hex) values ('51808F', 'Smalt Blue');
INSERT INTO colour (name, hex) values ('52001F', 'Castro');
INSERT INTO colour (name, hex) values ('520C17', 'Maroon Oak');
INSERT INTO colour (name, hex) values ('523C94', 'Gigas');
INSERT INTO colour (name, hex) values ('533455', 'Voodoo');
INSERT INTO colour (name, hex) values ('534491', 'Victoria');
INSERT INTO colour (name, hex) values ('53824B', 'Hippie Green');
INSERT INTO colour (name, hex) values ('541012', 'Heath');
INSERT INTO colour (name, hex) values ('544333', 'Judge Gray');
INSERT INTO colour (name, hex) values ('54534D', 'Fuscous Gray');
INSERT INTO colour (name, hex) values ('549019', 'Vida Loca');
INSERT INTO colour (name, hex) values ('55280C', 'Cioccolato');
INSERT INTO colour (name, hex) values ('555B10', 'Saratoga');
INSERT INTO colour (name, hex) values ('556D56', 'Finlandia');
INSERT INTO colour (name, hex) values ('5590D9', 'Havelock Blue');
INSERT INTO colour (name, hex) values ('56B4BE', 'Fountain Blue');
INSERT INTO colour (name, hex) values ('578363', 'Spring Leaves');
INSERT INTO colour (name, hex) values ('583401', 'Saddle Brown');
INSERT INTO colour (name, hex) values ('585562', 'Scarpa Flow');
INSERT INTO colour (name, hex) values ('587156', 'Cactus');
INSERT INTO colour (name, hex) values ('589AAF', 'Hippie Blue');
INSERT INTO colour (name, hex) values ('591D35', 'Wine Berry');
INSERT INTO colour (name, hex) values ('592804', 'Brown Bramble');
INSERT INTO colour (name, hex) values ('593737', 'Congo Brown');
INSERT INTO colour (name, hex) values ('594433', 'Millbrook');
INSERT INTO colour (name, hex) values ('5A6E9C', 'Waikawa Gray');
INSERT INTO colour (name, hex) values ('5A87A0', 'Horizon');
INSERT INTO colour (name, hex) values ('5B3013', 'Jambalaya');
INSERT INTO colour (name, hex) values ('5C0120', 'Bordeaux');
INSERT INTO colour (name, hex) values ('5C0536', 'Mulberry Wood');
INSERT INTO colour (name, hex) values ('5C2E01', 'Carnaby Tan');
INSERT INTO colour (name, hex) values ('5C5D75', 'Comet');
INSERT INTO colour (name, hex) values ('5D1E0F', 'Redwood');
INSERT INTO colour (name, hex) values ('5D4C51', 'Don Juan');
INSERT INTO colour (name, hex) values ('5D5C58', 'Chicago');
INSERT INTO colour (name, hex) values ('5D5E37', 'Verdigris');
INSERT INTO colour (name, hex) values ('5D7747', 'Dingley');
INSERT INTO colour (name, hex) values ('5DA19F', 'Breaker Bay');
INSERT INTO colour (name, hex) values ('5E483E', 'Kabul');
INSERT INTO colour (name, hex) values ('5E5D3B', 'Hemlock');
INSERT INTO colour (name, hex) values ('5F3D26', 'Irish Coffee');
INSERT INTO colour (name, hex) values ('5F5F6E', 'Mid Gray');
INSERT INTO colour (name, hex) values ('5F6672', 'Shuttle Gray');
INSERT INTO colour (name, hex) values ('5FA777', 'Aqua Forest');
INSERT INTO colour (name, hex) values ('5FB3AC', 'Tradewind');
INSERT INTO colour (name, hex) values ('604913', 'Horses Neck');
INSERT INTO colour (name, hex) values ('605B73', 'Smoky');
INSERT INTO colour (name, hex) values ('606E68', 'Corduroy');
INSERT INTO colour (name, hex) values ('6093D1', 'Danube');
INSERT INTO colour (name, hex) values ('612718', 'Espresso');
INSERT INTO colour (name, hex) values ('614051', 'Eggplant');
INSERT INTO colour (name, hex) values ('615D30', 'Costa Del Sol');
INSERT INTO colour (name, hex) values ('61845F', 'Glade Green');
INSERT INTO colour (name, hex) values ('622F30', 'Buccaneer');
INSERT INTO colour (name, hex) values ('623F2D', 'Quincy');
INSERT INTO colour (name, hex) values ('624E9A', 'Butterfly Bush');
INSERT INTO colour (name, hex) values ('625119', 'West Coast');
INSERT INTO colour (name, hex) values ('626649', 'Finch');
INSERT INTO colour (name, hex) values ('639A8F', 'Patina');
INSERT INTO colour (name, hex) values ('63B76C', 'Fern');
INSERT INTO colour (name, hex) values ('6456B7', 'Blue Violet');
INSERT INTO colour (name, hex) values ('646077', 'Dolphin');
INSERT INTO colour (name, hex) values ('646463', 'Storm Dust');
INSERT INTO colour (name, hex) values ('646A54', 'Siam');
INSERT INTO colour (name, hex) values ('646E75', 'Nevada');
INSERT INTO colour (name, hex) values ('6495ED', 'Cornflower Blue');
INSERT INTO colour (name, hex) values ('64CCDB', 'Viking');
INSERT INTO colour (name, hex) values ('65000B', 'Rosewood');
INSERT INTO colour (name, hex) values ('651A14', 'Cherrywood');
INSERT INTO colour (name, hex) values ('652DC1', 'Purple Heart');
INSERT INTO colour (name, hex) values ('657220', 'Fern Frond');
INSERT INTO colour (name, hex) values ('65745D', 'Willow Grove');
INSERT INTO colour (name, hex) values ('65869F', 'Hoki');
INSERT INTO colour (name, hex) values ('660045', 'Pompadour');
INSERT INTO colour (name, hex) values ('660099', 'Purple');
INSERT INTO colour (name, hex) values ('66023C', 'Tyrian Purple');
INSERT INTO colour (name, hex) values ('661010', 'Dark Tan');
INSERT INTO colour (name, hex) values ('66B58F', 'Silver Tree');
INSERT INTO colour (name, hex) values ('66FF00', 'Bright Green');
INSERT INTO colour (name, hex) values ('66FF66', 'Screamin'' Green');
INSERT INTO colour (name, hex) values ('67032D', 'Black Rose');
INSERT INTO colour (name, hex) values ('675FA6', 'Scampi');
INSERT INTO colour (name, hex) values ('676662', 'Ironside Gray');
INSERT INTO colour (name, hex) values ('678975', 'Viridian Green');
INSERT INTO colour (name, hex) values ('67A712', 'Christi');
INSERT INTO colour (name, hex) values ('683600', 'Nutmeg Wood Finish');
INSERT INTO colour (name, hex) values ('685558', 'Zambezi');
INSERT INTO colour (name, hex) values ('685E6E', 'Salt Box');
INSERT INTO colour (name, hex) values ('692545', 'Tawny Port');
INSERT INTO colour (name, hex) values ('692D54', 'Finn');
INSERT INTO colour (name, hex) values ('695F62', 'Scorpion');
INSERT INTO colour (name, hex) values ('697E9A', 'Lynch');
INSERT INTO colour (name, hex) values ('6A442E', 'Spice');
INSERT INTO colour (name, hex) values ('6A5D1B', 'Himalaya');
INSERT INTO colour (name, hex) values ('6A6051', 'Soya Bean');
INSERT INTO colour (name, hex) values ('6B2A14', 'Hairy Heath');
INSERT INTO colour (name, hex) values ('6B3FA0', 'Royal Purple');
INSERT INTO colour (name, hex) values ('6B4E31', 'Shingle Fawn');
INSERT INTO colour (name, hex) values ('6B5755', 'Dorado');
INSERT INTO colour (name, hex) values ('6B8BA2', 'Bermuda Gray');
INSERT INTO colour (name, hex) values ('6B8E23', 'Olive Drab');
INSERT INTO colour (name, hex) values ('6C3082', 'Eminence');
INSERT INTO colour (name, hex) values ('6CDAE7', 'Turquoise Blue');
INSERT INTO colour (name, hex) values ('6D0101', 'Lonestar');
INSERT INTO colour (name, hex) values ('6D5E54', 'Pine Cone');
INSERT INTO colour (name, hex) values ('6D6C6C', 'Dove Gray');
INSERT INTO colour (name, hex) values ('6D9292', 'Juniper');
INSERT INTO colour (name, hex) values ('6D92A1', 'Gothic');
INSERT INTO colour (name, hex) values ('6E0902', 'Red Oxide');
INSERT INTO colour (name, hex) values ('6E1D14', 'Moccaccino');
INSERT INTO colour (name, hex) values ('6E4826', 'Pickled Bean');
INSERT INTO colour (name, hex) values ('6E4B26', 'Dallas');
INSERT INTO colour (name, hex) values ('6E6D57', 'Kokoda');
INSERT INTO colour (name, hex) values ('6E7783', 'Pale Sky');
INSERT INTO colour (name, hex) values ('6F440C', 'Cafe Royale');
INSERT INTO colour (name, hex) values ('6F6A61', 'Flint');
INSERT INTO colour (name, hex) values ('6F8E63', 'Highland');
INSERT INTO colour (name, hex) values ('6F9D02', 'Limeade');
INSERT INTO colour (name, hex) values ('6FD0C5', 'Downy');
INSERT INTO colour (name, hex) values ('701C1C', 'Persian Plum');
INSERT INTO colour (name, hex) values ('704214', 'Sepia');
INSERT INTO colour (name, hex) values ('704A07', 'Antique Bronze');
INSERT INTO colour (name, hex) values ('704F50', 'Ferra');
INSERT INTO colour (name, hex) values ('706555', 'Coffee');
INSERT INTO colour (name, hex) values ('708090', 'Slate Gray');
INSERT INTO colour (name, hex) values ('711A00', 'Cedar Wood Finish');
INSERT INTO colour (name, hex) values ('71291D', 'Metallic Copper');
INSERT INTO colour (name, hex) values ('714693', 'Affair');
INSERT INTO colour (name, hex) values ('714AB2', 'Studio');
INSERT INTO colour (name, hex) values ('715D47', 'Tobacco Brown');
INSERT INTO colour (name, hex) values ('716338', 'Yellow Metal');
INSERT INTO colour (name, hex) values ('716B56', 'Peat');
INSERT INTO colour (name, hex) values ('716E10', 'Olivetone');
INSERT INTO colour (name, hex) values ('717486', 'Storm Gray');
INSERT INTO colour (name, hex) values ('718080', 'Sirocco');
INSERT INTO colour (name, hex) values ('71D9E2', 'Aquamarine Blue');
INSERT INTO colour (name, hex) values ('72010F', 'Venetian Red');
INSERT INTO colour (name, hex) values ('724A2F', 'Old Copper');
INSERT INTO colour (name, hex) values ('726D4E', 'Go Ben');
INSERT INTO colour (name, hex) values ('727B89', 'Raven');
INSERT INTO colour (name, hex) values ('731E8F', 'Seance');
INSERT INTO colour (name, hex) values ('734A12', 'Raw Umber');
INSERT INTO colour (name, hex) values ('736C9F', 'Kimberly');
INSERT INTO colour (name, hex) values ('736D58', 'Crocodile');
INSERT INTO colour (name, hex) values ('737829', 'Crete');
INSERT INTO colour (name, hex) values ('738678', 'Xanadu');
INSERT INTO colour (name, hex) values ('74640D', 'Spicy Mustard');
INSERT INTO colour (name, hex) values ('747D63', 'Limed Ash');
INSERT INTO colour (name, hex) values ('747D83', 'Rolling Stone');
INSERT INTO colour (name, hex) values ('748881', 'Blue Smoke');
INSERT INTO colour (name, hex) values ('749378', 'Laurel');
INSERT INTO colour (name, hex) values ('74C365', 'Mantis');
INSERT INTO colour (name, hex) values ('755A57', 'Russett');
INSERT INTO colour (name, hex) values ('7563A8', 'Deluge');
INSERT INTO colour (name, hex) values ('76395D', 'Cosmic');
INSERT INTO colour (name, hex) values ('7666C6', 'Blue Marguerite');
INSERT INTO colour (name, hex) values ('76BD17', 'Lima');
INSERT INTO colour (name, hex) values ('76D7EA', 'Sky Blue');
INSERT INTO colour (name, hex) values ('770F05', 'Dark Burgundy');
INSERT INTO colour (name, hex) values ('771F1F', 'Crown of Thorns');
INSERT INTO colour (name, hex) values ('773F1A', 'Walnut');
INSERT INTO colour (name, hex) values ('776F61', 'Pablo');
INSERT INTO colour (name, hex) values ('778120', 'Pacifika');
INSERT INTO colour (name, hex) values ('779E86', 'Oxley');
INSERT INTO colour (name, hex) values ('77DD77', 'Pastel Green');
INSERT INTO colour (name, hex) values ('780109', 'Japanese Maple');
INSERT INTO colour (name, hex) values ('782D19', 'Mocha');
INSERT INTO colour (name, hex) values ('782F16', 'Peanut');
INSERT INTO colour (name, hex) values ('78866B', 'Camouflage Green');
INSERT INTO colour (name, hex) values ('788A25', 'Wasabi');
INSERT INTO colour (name, hex) values ('788BBA', 'Ship Cove');
INSERT INTO colour (name, hex) values ('78A39C', 'Sea Nymph');
INSERT INTO colour (name, hex) values ('795D4C', 'Roman Coffee');
INSERT INTO colour (name, hex) values ('796878', 'Old Lavender');
INSERT INTO colour (name, hex) values ('796989', 'Rum');
INSERT INTO colour (name, hex) values ('796A78', 'Fedora');
INSERT INTO colour (name, hex) values ('796D62', 'Sandstone');
INSERT INTO colour (name, hex) values ('79DEEC', 'Spray');
INSERT INTO colour (name, hex) values ('7A013A', 'Siren');
INSERT INTO colour (name, hex) values ('7A58C1', 'Fuchsia Blue');
INSERT INTO colour (name, hex) values ('7A7A7A', 'Boulder');
INSERT INTO colour (name, hex) values ('7A89B8', 'Wild Blue Yonder');
INSERT INTO colour (name, hex) values ('7AC488', 'De York');
INSERT INTO colour (name, hex) values ('7B3801', 'Red Beech');
INSERT INTO colour (name, hex) values ('7B3F00', 'Cinnamon');
INSERT INTO colour (name, hex) values ('7B6608', 'Yukon Gold');
INSERT INTO colour (name, hex) values ('7B7874', 'Tapa');
INSERT INTO colour (name, hex) values ('7B7C94', 'Waterloo ');
INSERT INTO colour (name, hex) values ('7B8265', 'Flax Smoke');
INSERT INTO colour (name, hex) values ('7B9F80', 'Amulet');
INSERT INTO colour (name, hex) values ('7BA05B', 'Asparagus');
INSERT INTO colour (name, hex) values ('7C1C05', 'Kenyan Copper');
INSERT INTO colour (name, hex) values ('7C7631', 'Pesto');
INSERT INTO colour (name, hex) values ('7C778A', 'Topaz');
INSERT INTO colour (name, hex) values ('7C7B7A', 'Concord');
INSERT INTO colour (name, hex) values ('7C7B82', 'Jumbo');
INSERT INTO colour (name, hex) values ('7C881A', 'Trendy Green');
INSERT INTO colour (name, hex) values ('7CA1A6', 'Gumbo');
INSERT INTO colour (name, hex) values ('7CB0A1', 'Acapulco');
INSERT INTO colour (name, hex) values ('7CB7BB', 'Neptune');
INSERT INTO colour (name, hex) values ('7D2C14', 'Pueblo');
INSERT INTO colour (name, hex) values ('7DA98D', 'Bay Leaf');
INSERT INTO colour (name, hex) values ('7DC8F7', 'Malibu');
INSERT INTO colour (name, hex) values ('7DD8C6', 'Bermuda');
INSERT INTO colour (name, hex) values ('7E3A15', 'Copper Canyon');
INSERT INTO colour (name, hex) values ('7F1734', 'Claret');
INSERT INTO colour (name, hex) values ('7F3A02', 'Peru Tan');
INSERT INTO colour (name, hex) values ('7F626D', 'Falcon');
INSERT INTO colour (name, hex) values ('7F7589', 'Mobster');
INSERT INTO colour (name, hex) values ('7F76D3', 'Moody Blue');
INSERT INTO colour (name, hex) values ('7FFF00', 'Chartreuse');
INSERT INTO colour (name, hex) values ('7FFFD4', 'Aquamarine');
INSERT INTO colour (name, hex) values ('800000', 'Maroon');
INSERT INTO colour (name, hex) values ('800B47', 'Rose Bud Cherry');
INSERT INTO colour (name, hex) values ('801818', 'Falu Red');
INSERT INTO colour (name, hex) values ('80341F', 'Red Robin');
INSERT INTO colour (name, hex) values ('803790', 'Vivid Violet');
INSERT INTO colour (name, hex) values ('80461B', 'Russet');
INSERT INTO colour (name, hex) values ('807E79', 'Friar Gray');
INSERT INTO colour (name, hex) values ('808000', 'Olive');
INSERT INTO colour (name, hex) values ('808080', 'Gray');
INSERT INTO colour (name, hex) values ('80B3AE', 'Gulf Stream');
INSERT INTO colour (name, hex) values ('80B3C4', 'Glacier');
INSERT INTO colour (name, hex) values ('80CCEA', 'Seagull');
INSERT INTO colour (name, hex) values ('81422C', 'Nutmeg');
INSERT INTO colour (name, hex) values ('816E71', 'Spicy Pink');
INSERT INTO colour (name, hex) values ('817377', 'Empress');
INSERT INTO colour (name, hex) values ('819885', 'Spanish Green');
INSERT INTO colour (name, hex) values ('826F65', 'Sand Dune');
INSERT INTO colour (name, hex) values ('828685', 'Gunsmoke');
INSERT INTO colour (name, hex) values ('828F72', 'Battleship Gray');
INSERT INTO colour (name, hex) values ('831923', 'Merlot');
INSERT INTO colour (name, hex) values ('837050', 'Shadow');
INSERT INTO colour (name, hex) values ('83AA5D', 'Chelsea Cucumber');
INSERT INTO colour (name, hex) values ('83D0C6', 'Monte Carlo');
INSERT INTO colour (name, hex) values ('843179', 'Plum');
INSERT INTO colour (name, hex) values ('84A0A0', 'Granny Smith');
INSERT INTO colour (name, hex) values ('8581D9', 'Chetwode Blue');
INSERT INTO colour (name, hex) values ('858470', 'Bandicoot');
INSERT INTO colour (name, hex) values ('859FAF', 'Bali Hai');
INSERT INTO colour (name, hex) values ('85C4CC', 'Half Baked');
INSERT INTO colour (name, hex) values ('860111', 'Red Devil');
INSERT INTO colour (name, hex) values ('863C3C', 'Lotus');
INSERT INTO colour (name, hex) values ('86483C', 'Ironstone');
INSERT INTO colour (name, hex) values ('864D1E', 'Bull Shot');
INSERT INTO colour (name, hex) values ('86560A', 'Rusty Nail');
INSERT INTO colour (name, hex) values ('868974', 'Bitter');
INSERT INTO colour (name, hex) values ('86949F', 'Regent Gray');
INSERT INTO colour (name, hex) values ('871550', 'Disco');
INSERT INTO colour (name, hex) values ('87756E', 'Americano');
INSERT INTO colour (name, hex) values ('877C7B', 'Hurricane');
INSERT INTO colour (name, hex) values ('878D91', 'Oslo Gray');
INSERT INTO colour (name, hex) values ('87AB39', 'Sushi');
INSERT INTO colour (name, hex) values ('885342', 'Spicy Mix');
INSERT INTO colour (name, hex) values ('886221', 'Kumera');
INSERT INTO colour (name, hex) values ('888387', 'Suva Gray');
INSERT INTO colour (name, hex) values ('888D65', 'Avocado');
INSERT INTO colour (name, hex) values ('893456', 'Camelot');
INSERT INTO colour (name, hex) values ('893843', 'Solid Pink');
INSERT INTO colour (name, hex) values ('894367', 'Cannon Pink');
INSERT INTO colour (name, hex) values ('897D6D', 'Makara');
INSERT INTO colour (name, hex) values ('8A3324', 'Burnt Umber');
INSERT INTO colour (name, hex) values ('8A73D6', 'True V');
INSERT INTO colour (name, hex) values ('8A8360', 'Clay Creek');
INSERT INTO colour (name, hex) values ('8A8389', 'Monsoon');
INSERT INTO colour (name, hex) values ('8A8F8A', 'Stack');
INSERT INTO colour (name, hex) values ('8AB9F1', 'Jordy Blue');
INSERT INTO colour (name, hex) values ('8B00FF', 'Electric Violet');
INSERT INTO colour (name, hex) values ('8B0723', 'Monarch');
INSERT INTO colour (name, hex) values ('8B6B0B', 'Corn Harvest');
INSERT INTO colour (name, hex) values ('8B8470', 'Olive Haze');
INSERT INTO colour (name, hex) values ('8B847E', 'Schooner');
INSERT INTO colour (name, hex) values ('8B8680', 'Natural Gray');
INSERT INTO colour (name, hex) values ('8B9C90', 'Mantle');
INSERT INTO colour (name, hex) values ('8B9FEE', 'Portage');
INSERT INTO colour (name, hex) values ('8BA690', 'Envy');
INSERT INTO colour (name, hex) values ('8BA9A5', 'Cascade');
INSERT INTO colour (name, hex) values ('8BE6D8', 'Riptide');
INSERT INTO colour (name, hex) values ('8C055E', 'Cardinal Pink');
INSERT INTO colour (name, hex) values ('8C472F', 'Mule Fawn');
INSERT INTO colour (name, hex) values ('8C5738', 'Potters Clay');
INSERT INTO colour (name, hex) values ('8C6495', 'Trendy Pink');
INSERT INTO colour (name, hex) values ('8D0226', 'Paprika');
INSERT INTO colour (name, hex) values ('8D3D38', 'Sanguine Brown');
INSERT INTO colour (name, hex) values ('8D3F3F', 'Tosca');
INSERT INTO colour (name, hex) values ('8D7662', 'Cement');
INSERT INTO colour (name, hex) values ('8D8974', 'Granite Green');
INSERT INTO colour (name, hex) values ('8D90A1', 'Manatee');
INSERT INTO colour (name, hex) values ('8DA8CC', 'Polo Blue');
INSERT INTO colour (name, hex) values ('8E0000', 'Red Berry');
INSERT INTO colour (name, hex) values ('8E4D1E', 'Rope');
INSERT INTO colour (name, hex) values ('8E6F70', 'Opium');
INSERT INTO colour (name, hex) values ('8E775E', 'Domino');
INSERT INTO colour (name, hex) values ('8E8190', 'Mamba');
INSERT INTO colour (name, hex) values ('8EABC1', 'Nepal');
INSERT INTO colour (name, hex) values ('8F021C', 'Pohutukawa');
INSERT INTO colour (name, hex) values ('8F3E33', 'El Salva');
INSERT INTO colour (name, hex) values ('8F4B0E', 'Korma');
INSERT INTO colour (name, hex) values ('8F8176', 'Squirrel');
INSERT INTO colour (name, hex) values ('8FD6B4', 'Vista Blue');
INSERT INTO colour (name, hex) values ('900020', 'Burgundy');
INSERT INTO colour (name, hex) values ('901E1E', 'Old Brick');
INSERT INTO colour (name, hex) values ('907874', 'Hemp');
INSERT INTO colour (name, hex) values ('907B71', 'Almond Frost');
INSERT INTO colour (name, hex) values ('908D39', 'Sycamore');
INSERT INTO colour (name, hex) values ('92000A', 'Sangria');
INSERT INTO colour (name, hex) values ('924321', 'Cumin');
INSERT INTO colour (name, hex) values ('926F5B', 'Beaver');
INSERT INTO colour (name, hex) values ('928573', 'Stonewall');
INSERT INTO colour (name, hex) values ('928590', 'Venus');
INSERT INTO colour (name, hex) values ('9370DB', 'Medium Purple');
INSERT INTO colour (name, hex) values ('93CCEA', 'Cornflower');
INSERT INTO colour (name, hex) values ('93DFB8', 'Algae Green');
INSERT INTO colour (name, hex) values ('944747', 'Copper Rust');
INSERT INTO colour (name, hex) values ('948771', 'Arrowtown');
INSERT INTO colour (name, hex) values ('950015', 'Scarlett');
INSERT INTO colour (name, hex) values ('956387', 'Strikemaster');
INSERT INTO colour (name, hex) values ('959396', 'Mountain Mist');
INSERT INTO colour (name, hex) values ('960018', 'Carmine');
INSERT INTO colour (name, hex) values ('964B00', 'Brown');
INSERT INTO colour (name, hex) values ('967059', 'Leather');
INSERT INTO colour (name, hex) values ('9678B6', 'Purple Mountain''s Majesty');
INSERT INTO colour (name, hex) values ('967BB6', 'Lavender Purple');
INSERT INTO colour (name, hex) values ('96A8A1', 'Pewter');
INSERT INTO colour (name, hex) values ('96BBAB', 'Summer Green');
INSERT INTO colour (name, hex) values ('97605D', 'Au Chico');
INSERT INTO colour (name, hex) values ('9771B5', 'Wisteria');
INSERT INTO colour (name, hex) values ('97CD2D', 'Atlantis');
INSERT INTO colour (name, hex) values ('983D61', 'Vin Rouge');
INSERT INTO colour (name, hex) values ('9874D3', 'Lilac Bush');
INSERT INTO colour (name, hex) values ('98777B', 'Bazaar');
INSERT INTO colour (name, hex) values ('98811B', 'Hacienda');
INSERT INTO colour (name, hex) values ('988D77', 'Pale Oyster');
INSERT INTO colour (name, hex) values ('98FF98', 'Mint Green');
INSERT INTO colour (name, hex) values ('990066', 'Fresh Eggplant');
INSERT INTO colour (name, hex) values ('991199', 'Violet Eggplant');
INSERT INTO colour (name, hex) values ('991613', 'Tamarillo');
INSERT INTO colour (name, hex) values ('991B07', 'Totem Pole');
INSERT INTO colour (name, hex) values ('996666', 'Copper Rose');
INSERT INTO colour (name, hex) values ('9966CC', 'Amethyst');
INSERT INTO colour (name, hex) values ('997A8D', 'Mountbatten Pink');
INSERT INTO colour (name, hex) values ('9999CC', 'Blue Bell');
INSERT INTO colour (name, hex) values ('9A3820', 'Prairie Sand');
INSERT INTO colour (name, hex) values ('9A6E61', 'Toast');
INSERT INTO colour (name, hex) values ('9A9577', 'Gurkha');
INSERT INTO colour (name, hex) values ('9AB973', 'Olivine');
INSERT INTO colour (name, hex) values ('9AC2B8', 'Shadow Green');
INSERT INTO colour (name, hex) values ('9B4703', 'Oregon');
INSERT INTO colour (name, hex) values ('9B9E8F', 'Lemon Grass');
INSERT INTO colour (name, hex) values ('9C3336', 'Stiletto');
INSERT INTO colour (name, hex) values ('9D5616', 'Hawaiian Tan');
INSERT INTO colour (name, hex) values ('9DACB7', 'Gull Gray');
INSERT INTO colour (name, hex) values ('9DC209', 'Pistachio');
INSERT INTO colour (name, hex) values ('9DE093', 'Granny Smith Apple');
INSERT INTO colour (name, hex) values ('9DE5FF', 'Anakiwa');
INSERT INTO colour (name, hex) values ('9E5302', 'Chelsea Gem');
INSERT INTO colour (name, hex) values ('9E5B40', 'Sepia Skin');
INSERT INTO colour (name, hex) values ('9EA587', 'Sage');
INSERT INTO colour (name, hex) values ('9EA91F', 'Citron');
INSERT INTO colour (name, hex) values ('9EB1CD', 'Rock Blue');
INSERT INTO colour (name, hex) values ('9EDEE0', 'Morning Glory');
INSERT INTO colour (name, hex) values ('9F381D', 'Cognac');
INSERT INTO colour (name, hex) values ('9F821C', 'Reef Gold');
INSERT INTO colour (name, hex) values ('9F9F9C', 'Star Dust');
INSERT INTO colour (name, hex) values ('9FA0B1', 'Santas Gray');
INSERT INTO colour (name, hex) values ('9FD7D3', 'Sinbad');
INSERT INTO colour (name, hex) values ('9FDD8C', 'Feijoa');
INSERT INTO colour (name, hex) values ('A02712', 'Tabasco');
INSERT INTO colour (name, hex) values ('A1750D', 'Buttered Rum');
INSERT INTO colour (name, hex) values ('A1ADB5', 'Hit Gray');
INSERT INTO colour (name, hex) values ('A1C50A', 'Citrus');
INSERT INTO colour (name, hex) values ('A1DAD7', 'Aqua Island');
INSERT INTO colour (name, hex) values ('A1E9DE', 'Water Leaf');
INSERT INTO colour (name, hex) values ('A2006D', 'Flirt');
INSERT INTO colour (name, hex) values ('A23B6C', 'Rouge');
INSERT INTO colour (name, hex) values ('A26645', 'Cape Palliser');
INSERT INTO colour (name, hex) values ('A2AAB3', 'Gray Chateau');
INSERT INTO colour (name, hex) values ('A2AEAB', 'Edward');
INSERT INTO colour (name, hex) values ('A3807B', 'Pharlap');
INSERT INTO colour (name, hex) values ('A397B4', 'Amethyst Smoke');
INSERT INTO colour (name, hex) values ('A3E3ED', 'Blizzard Blue');
INSERT INTO colour (name, hex) values ('A4A49D', 'Delta');
INSERT INTO colour (name, hex) values ('A4A6D3', 'Wistful');
INSERT INTO colour (name, hex) values ('A4AF6E', 'Green Smoke');
INSERT INTO colour (name, hex) values ('A50B5E', 'Jazzberry Jam');
INSERT INTO colour (name, hex) values ('A59B91', 'Zorba');
INSERT INTO colour (name, hex) values ('A5CB0C', 'Bahia');
INSERT INTO colour (name, hex) values ('A62F20', 'Roof Terracotta');
INSERT INTO colour (name, hex) values ('A65529', 'Paarl');
INSERT INTO colour (name, hex) values ('A68B5B', 'Barley Corn');
INSERT INTO colour (name, hex) values ('A69279', 'Donkey Brown');
INSERT INTO colour (name, hex) values ('A6A29A', 'Dawn');
INSERT INTO colour (name, hex) values ('A72525', 'Mexican Red');
INSERT INTO colour (name, hex) values ('A7882C', 'Luxor Gold');
INSERT INTO colour (name, hex) values ('A85307', 'Rich Gold');
INSERT INTO colour (name, hex) values ('A86515', 'Reno Sand');
INSERT INTO colour (name, hex) values ('A86B6B', 'Coral Tree');
INSERT INTO colour (name, hex) values ('A8989B', 'Dusty Gray');
INSERT INTO colour (name, hex) values ('A899E6', 'Dull Lavender');
INSERT INTO colour (name, hex) values ('A8A589', 'Tallow');
INSERT INTO colour (name, hex) values ('A8AE9C', 'Bud');
INSERT INTO colour (name, hex) values ('A8AF8E', 'Locust');
INSERT INTO colour (name, hex) values ('A8BD9F', 'Norway');
INSERT INTO colour (name, hex) values ('A8E3BD', 'Chinook');
INSERT INTO colour (name, hex) values ('A9A491', 'Gray Olive');
INSERT INTO colour (name, hex) values ('A9ACB6', 'Aluminium');
INSERT INTO colour (name, hex) values ('A9B2C3', 'Cadet Blue');
INSERT INTO colour (name, hex) values ('A9B497', 'Schist');
INSERT INTO colour (name, hex) values ('A9BDBF', 'Tower Gray');
INSERT INTO colour (name, hex) values ('A9BEF2', 'Perano');
INSERT INTO colour (name, hex) values ('A9C6C2', 'Opal');
INSERT INTO colour (name, hex) values ('AA375A', 'Night Shadz');
INSERT INTO colour (name, hex) values ('AA4203', 'Fire');
INSERT INTO colour (name, hex) values ('AA8B5B', 'Muesli');
INSERT INTO colour (name, hex) values ('AA8D6F', 'Sandal');
INSERT INTO colour (name, hex) values ('AAA5A9', 'Shady Lady');
INSERT INTO colour (name, hex) values ('AAA9CD', 'Logan');
INSERT INTO colour (name, hex) values ('AAABB7', 'Spun Pearl');
INSERT INTO colour (name, hex) values ('AAD6E6', 'Regent St Blue');
INSERT INTO colour (name, hex) values ('AAF0D1', 'Magic Mint');
INSERT INTO colour (name, hex) values ('AB0563', 'Lipstick');
INSERT INTO colour (name, hex) values ('AB3472', 'Royal Heath');
INSERT INTO colour (name, hex) values ('AB917A', 'Sandrift');
INSERT INTO colour (name, hex) values ('ABA0D9', 'Cold Purple');
INSERT INTO colour (name, hex) values ('ABA196', 'Bronco');
INSERT INTO colour (name, hex) values ('AC8A56', 'Limed Oak');
INSERT INTO colour (name, hex) values ('AC91CE', 'East Side');
INSERT INTO colour (name, hex) values ('AC9E22', 'Lemon Ginger');
INSERT INTO colour (name, hex) values ('ACA494', 'Napa');
INSERT INTO colour (name, hex) values ('ACA586', 'Hillary');
INSERT INTO colour (name, hex) values ('ACA59F', 'Cloudy');
INSERT INTO colour (name, hex) values ('ACACAC', 'Silver Chalice');
INSERT INTO colour (name, hex) values ('ACB78E', 'Swamp Green');
INSERT INTO colour (name, hex) values ('ACCBB1', 'Spring Rain');
INSERT INTO colour (name, hex) values ('ACDD4D', 'Conifer');
INSERT INTO colour (name, hex) values ('ACE1AF', 'Celadon');
INSERT INTO colour (name, hex) values ('AD781B', 'Mandalay');
INSERT INTO colour (name, hex) values ('ADBED1', 'Casper');
INSERT INTO colour (name, hex) values ('ADDFAD', 'Moss Green');
INSERT INTO colour (name, hex) values ('ADE6C4', 'Padua');
INSERT INTO colour (name, hex) values ('ADFF2F', 'Green Yellow');
INSERT INTO colour (name, hex) values ('AE4560', 'Hippie Pink');
INSERT INTO colour (name, hex) values ('AE6020', 'Desert');
INSERT INTO colour (name, hex) values ('AE809E', 'Bouquet');
INSERT INTO colour (name, hex) values ('AF4035', 'Medium Carmine');
INSERT INTO colour (name, hex) values ('AF4D43', 'Apple Blossom');
INSERT INTO colour (name, hex) values ('AF593E', 'Brown Rust');
INSERT INTO colour (name, hex) values ('AF8751', 'Driftwood');
INSERT INTO colour (name, hex) values ('AF8F2C', 'Alpine');
INSERT INTO colour (name, hex) values ('AF9F1C', 'Lucky');
INSERT INTO colour (name, hex) values ('AFA09E', 'Martini');
INSERT INTO colour (name, hex) values ('AFB1B8', 'Bombay');
INSERT INTO colour (name, hex) values ('AFBDD9', 'Pigeon Post');
INSERT INTO colour (name, hex) values ('B04C6A', 'Cadillac');
INSERT INTO colour (name, hex) values ('B05D54', 'Matrix');
INSERT INTO colour (name, hex) values ('B05E81', 'Tapestry');
INSERT INTO colour (name, hex) values ('B06608', 'Mai Tai');
INSERT INTO colour (name, hex) values ('B09A95', 'Del Rio');
INSERT INTO colour (name, hex) values ('B0E0E6', 'Powder Blue');
INSERT INTO colour (name, hex) values ('B0E313', 'Inch Worm');
INSERT INTO colour (name, hex) values ('B10000', 'Bright Red');
INSERT INTO colour (name, hex) values ('B14A0B', 'Vesuvius');
INSERT INTO colour (name, hex) values ('B1610B', 'Pumpkin Skin');
INSERT INTO colour (name, hex) values ('B16D52', 'Santa Fe');
INSERT INTO colour (name, hex) values ('B19461', 'Teak');
INSERT INTO colour (name, hex) values ('B1E2C1', 'Fringy Flower');
INSERT INTO colour (name, hex) values ('B1F4E7', 'Ice Cold');
INSERT INTO colour (name, hex) values ('B20931', 'Shiraz');
INSERT INTO colour (name, hex) values ('B2A1EA', 'Biloba Flower');
INSERT INTO colour (name, hex) values ('B32D29', 'Tall Poppy');
INSERT INTO colour (name, hex) values ('B35213', 'Fiery Orange');
INSERT INTO colour (name, hex) values ('B38007', 'Hot Toddy');
INSERT INTO colour (name, hex) values ('B3AF95', 'Taupe Gray');
INSERT INTO colour (name, hex) values ('B3C110', 'La Rioja');
INSERT INTO colour (name, hex) values ('B43332', 'Well Read');
INSERT INTO colour (name, hex) values ('B44668', 'Blush');
INSERT INTO colour (name, hex) values ('B4CFD3', 'Jungle Mist');
INSERT INTO colour (name, hex) values ('B57281', 'Turkish Rose');
INSERT INTO colour (name, hex) values ('B57EDC', 'Lavender');
INSERT INTO colour (name, hex) values ('B5A27F', 'Mongoose');
INSERT INTO colour (name, hex) values ('B5B35C', 'Olive Green');
INSERT INTO colour (name, hex) values ('B5D2CE', 'Jet Stream');
INSERT INTO colour (name, hex) values ('B5ECDF', 'Cruise');
INSERT INTO colour (name, hex) values ('B6316C', 'Hibiscus');
INSERT INTO colour (name, hex) values ('B69D98', 'Thatch');
INSERT INTO colour (name, hex) values ('B6B095', 'Heathered Gray');
INSERT INTO colour (name, hex) values ('B6BAA4', 'Eagle');
INSERT INTO colour (name, hex) values ('B6D1EA', 'Spindle');
INSERT INTO colour (name, hex) values ('B6D3BF', 'Gum Leaf');
INSERT INTO colour (name, hex) values ('B7410E', 'Rust');
INSERT INTO colour (name, hex) values ('B78E5C', 'Muddy Waters');
INSERT INTO colour (name, hex) values ('B7A214', 'Sahara');
INSERT INTO colour (name, hex) values ('B7A458', 'Husk');
INSERT INTO colour (name, hex) values ('B7B1B1', 'Nobel');
INSERT INTO colour (name, hex) values ('B7C3D0', 'Heather');
INSERT INTO colour (name, hex) values ('B7F0BE', 'Madang');
INSERT INTO colour (name, hex) values ('B81104', 'Milano Red');
INSERT INTO colour (name, hex) values ('B87333', 'Copper');
INSERT INTO colour (name, hex) values ('B8B56A', 'Gimblet');
INSERT INTO colour (name, hex) values ('B8C1B1', 'Green Spring');
INSERT INTO colour (name, hex) values ('B8C25D', 'Celery');
INSERT INTO colour (name, hex) values ('B8E0F9', 'Sail');
INSERT INTO colour (name, hex) values ('B94E48', 'Chestnut');
INSERT INTO colour (name, hex) values ('B95140', 'Crail');
INSERT INTO colour (name, hex) values ('B98D28', 'Marigold');
INSERT INTO colour (name, hex) values ('B9C46A', 'Wild Willow');
INSERT INTO colour (name, hex) values ('B9C8AC', 'Rainee');
INSERT INTO colour (name, hex) values ('BA0101', 'Guardsman Red');
INSERT INTO colour (name, hex) values ('BA450C', 'Rock Spray');
INSERT INTO colour (name, hex) values ('BA6F1E', 'Bourbon');
INSERT INTO colour (name, hex) values ('BA7F03', 'Pirate Gold');
INSERT INTO colour (name, hex) values ('BAB1A2', 'Nomad');
INSERT INTO colour (name, hex) values ('BAC7C9', 'Submarine');
INSERT INTO colour (name, hex) values ('BAEEF9', 'Charlotte');
INSERT INTO colour (name, hex) values ('BB3385', 'Medium Red Violet');
INSERT INTO colour (name, hex) values ('BB8983', 'Brandy Rose');
INSERT INTO colour (name, hex) values ('BBD009', 'Rio Grande');
INSERT INTO colour (name, hex) values ('BBD7C1', 'Surf');
INSERT INTO colour (name, hex) values ('BCC9C2', 'Powder Ash');
INSERT INTO colour (name, hex) values ('BD5E2E', 'Tuscany');
INSERT INTO colour (name, hex) values ('BD978E', 'Quicksand');
INSERT INTO colour (name, hex) values ('BDB1A8', 'Silk');
INSERT INTO colour (name, hex) values ('BDB2A1', 'Malta');
INSERT INTO colour (name, hex) values ('BDB3C7', 'Chatelle');
INSERT INTO colour (name, hex) values ('BDBBD7', 'Lavender Gray');
INSERT INTO colour (name, hex) values ('BDBDC6', 'French Gray');
INSERT INTO colour (name, hex) values ('BDC8B3', 'Clay Ash');
INSERT INTO colour (name, hex) values ('BDC9CE', 'Loblolly');
INSERT INTO colour (name, hex) values ('BDEDFD', 'French Pass');
INSERT INTO colour (name, hex) values ('BEA6C3', 'London Hue');
INSERT INTO colour (name, hex) values ('BEB5B7', 'Pink Swan');
INSERT INTO colour (name, hex) values ('BEDE0D', 'Fuego');
INSERT INTO colour (name, hex) values ('BF5500', 'Rose of Sharon');
INSERT INTO colour (name, hex) values ('BFB8B0', 'Tide');
INSERT INTO colour (name, hex) values ('BFBED8', 'Blue Haze');
INSERT INTO colour (name, hex) values ('BFC1C2', 'Silver Sand');
INSERT INTO colour (name, hex) values ('BFC921', 'Key Lime Pie');
INSERT INTO colour (name, hex) values ('BFDBE2', 'Ziggurat');
INSERT INTO colour (name, hex) values ('BFFF00', 'Lime');
INSERT INTO colour (name, hex) values ('C02B18', 'Thunderbird');
INSERT INTO colour (name, hex) values ('C04737', 'Mojo');
INSERT INTO colour (name, hex) values ('C08081', 'Old Rose');
INSERT INTO colour (name, hex) values ('C0C0C0', 'Silver');
INSERT INTO colour (name, hex) values ('C0D3B9', 'Pale Leaf');
INSERT INTO colour (name, hex) values ('C0D8B6', 'Pixie Green');
INSERT INTO colour (name, hex) values ('C1440E', 'Tia Maria');
INSERT INTO colour (name, hex) values ('C154C1', 'Fuchsia Pink');
INSERT INTO colour (name, hex) values ('C1A004', 'Buddha Gold');
INSERT INTO colour (name, hex) values ('C1B7A4', 'Bison Hide');
INSERT INTO colour (name, hex) values ('C1BAB0', 'Tea');
INSERT INTO colour (name, hex) values ('C1BECD', 'Gray Suit');
INSERT INTO colour (name, hex) values ('C1D7B0', 'Sprout');
INSERT INTO colour (name, hex) values ('C1F07C', 'Sulu');
INSERT INTO colour (name, hex) values ('C26B03', 'Indochine');
INSERT INTO colour (name, hex) values ('C2955D', 'Twine');
INSERT INTO colour (name, hex) values ('C2BDB6', 'Cotton Seed');
INSERT INTO colour (name, hex) values ('C2CAC4', 'Pumice');
INSERT INTO colour (name, hex) values ('C2E8E5', 'Jagged Ice');
INSERT INTO colour (name, hex) values ('C32148', 'Maroon Flush');
INSERT INTO colour (name, hex) values ('C3B091', 'Indian Khaki');
INSERT INTO colour (name, hex) values ('C3BFC1', 'Pale Slate');
INSERT INTO colour (name, hex) values ('C3C3BD', 'Gray Nickel');
INSERT INTO colour (name, hex) values ('C3CDE6', 'Periwinkle Gray');
INSERT INTO colour (name, hex) values ('C3D1D1', 'Tiara');
INSERT INTO colour (name, hex) values ('C3DDF9', 'Tropical Blue');
INSERT INTO colour (name, hex) values ('C41E3A', 'Cardinal');
INSERT INTO colour (name, hex) values ('C45655', 'Fuzzy Wuzzy Brown');
INSERT INTO colour (name, hex) values ('C45719', 'Orange Roughy');
INSERT INTO colour (name, hex) values ('C4C4BC', 'Mist Gray');
INSERT INTO colour (name, hex) values ('C4D0B0', 'Coriander');
INSERT INTO colour (name, hex) values ('C4F4EB', 'Mint Tulip');
INSERT INTO colour (name, hex) values ('C54B8C', 'Mulberry');
INSERT INTO colour (name, hex) values ('C59922', 'Nugget');
INSERT INTO colour (name, hex) values ('C5994B', 'Tussock');
INSERT INTO colour (name, hex) values ('C5DBCA', 'Sea Mist');
INSERT INTO colour (name, hex) values ('C5E17A', 'Yellow Green');
INSERT INTO colour (name, hex) values ('C62D42', 'Brick Red');
INSERT INTO colour (name, hex) values ('C6726B', 'Contessa');
INSERT INTO colour (name, hex) values ('C69191', 'Oriental Pink');
INSERT INTO colour (name, hex) values ('C6A84B', 'Roti');
INSERT INTO colour (name, hex) values ('C6C3B5', 'Ash');
INSERT INTO colour (name, hex) values ('C6C8BD', 'Kangaroo');
INSERT INTO colour (name, hex) values ('C6E610', 'Las Palmas');
INSERT INTO colour (name, hex) values ('C7031E', 'Monza');
INSERT INTO colour (name, hex) values ('C71585', 'Red Violet');
INSERT INTO colour (name, hex) values ('C7BCA2', 'Coral Reef');
INSERT INTO colour (name, hex) values ('C7C1FF', 'Melrose');
INSERT INTO colour (name, hex) values ('C7C4BF', 'Cloud');
INSERT INTO colour (name, hex) values ('C7C9D5', 'Ghost');
INSERT INTO colour (name, hex) values ('C7CD90', 'Pine Glade');
INSERT INTO colour (name, hex) values ('C7DDE5', 'Botticelli');
INSERT INTO colour (name, hex) values ('C88A65', 'Antique Brass');
INSERT INTO colour (name, hex) values ('C8A2C8', 'Lilac');
INSERT INTO colour (name, hex) values ('C8A528', 'Hokey Pokey');
INSERT INTO colour (name, hex) values ('C8AABF', 'Lily');
INSERT INTO colour (name, hex) values ('C8B568', 'Laser');
INSERT INTO colour (name, hex) values ('C8E3D7', 'Edgewater');
INSERT INTO colour (name, hex) values ('C96323', 'Piper');
INSERT INTO colour (name, hex) values ('C99415', 'Pizza');
INSERT INTO colour (name, hex) values ('C9A0DC', 'Light Wisteria');
INSERT INTO colour (name, hex) values ('C9B29B', 'Rodeo Dust');
INSERT INTO colour (name, hex) values ('C9B35B', 'Sundance');
INSERT INTO colour (name, hex) values ('C9B93B', 'Earls Green');
INSERT INTO colour (name, hex) values ('C9C0BB', 'Silver Rust');
INSERT INTO colour (name, hex) values ('C9D9D2', 'Conch');
INSERT INTO colour (name, hex) values ('C9FFA2', 'Reef');
INSERT INTO colour (name, hex) values ('C9FFE5', 'Aero Blue');
INSERT INTO colour (name, hex) values ('CA3435', 'Flush Mahogany');
INSERT INTO colour (name, hex) values ('CABB48', 'Turmeric');
INSERT INTO colour (name, hex) values ('CADCD4', 'Paris White');
INSERT INTO colour (name, hex) values ('CAE00D', 'Bitter Lemon');
INSERT INTO colour (name, hex) values ('CAE6DA', 'Skeptic');
INSERT INTO colour (name, hex) values ('CB8FA9', 'Viola');
INSERT INTO colour (name, hex) values ('CBCAB6', 'Foggy Gray');
INSERT INTO colour (name, hex) values ('CBD3B0', 'Green Mist');
INSERT INTO colour (name, hex) values ('CBDBD6', 'Nebula');
INSERT INTO colour (name, hex) values ('CC3333', 'Persian Red');
INSERT INTO colour (name, hex) values ('CC5500', 'Burnt Orange');
INSERT INTO colour (name, hex) values ('CC7722', 'Ochre');
INSERT INTO colour (name, hex) values ('CC8899', 'Puce');
INSERT INTO colour (name, hex) values ('CCCAA8', 'Thistle Green');
INSERT INTO colour (name, hex) values ('CCCCFF', 'Periwinkle');
INSERT INTO colour (name, hex) values ('CCFF00', 'Electric Lime');
INSERT INTO colour (name, hex) values ('CD5700', 'Tenn');
INSERT INTO colour (name, hex) values ('CD5C5C', 'Chestnut Rose');
INSERT INTO colour (name, hex) values ('CD8429', 'Brandy Punch');
INSERT INTO colour (name, hex) values ('CDF4FF', 'Onahau');
INSERT INTO colour (name, hex) values ('CEB98F', 'Sorrell Brown');
INSERT INTO colour (name, hex) values ('CEBABA', 'Cold Turkey');
INSERT INTO colour (name, hex) values ('CEC291', 'Yuma');
INSERT INTO colour (name, hex) values ('CEC7A7', 'Chino');
INSERT INTO colour (name, hex) values ('CFA39D', 'Eunry');
INSERT INTO colour (name, hex) values ('CFB53B', 'Old Gold');
INSERT INTO colour (name, hex) values ('CFDCCF', 'Tasman');
INSERT INTO colour (name, hex) values ('CFE5D2', 'Surf Crest');
INSERT INTO colour (name, hex) values ('CFF9F3', 'Humming Bird');
INSERT INTO colour (name, hex) values ('CFFAF4', 'Scandal');
INSERT INTO colour (name, hex) values ('D05F04', 'Red Stage');
INSERT INTO colour (name, hex) values ('D06DA1', 'Hopbush');
INSERT INTO colour (name, hex) values ('D07D12', 'Meteor');
INSERT INTO colour (name, hex) values ('D0BEF8', 'Perfume');
INSERT INTO colour (name, hex) values ('D0C0E5', 'Prelude');
INSERT INTO colour (name, hex) values ('D0F0C0', 'Tea Green');
INSERT INTO colour (name, hex) values ('D18F1B', 'Geebung');
INSERT INTO colour (name, hex) values ('D1BEA8', 'Vanilla');
INSERT INTO colour (name, hex) values ('D1C6B4', 'Soft Amber');
INSERT INTO colour (name, hex) values ('D1D2CA', 'Celeste');
INSERT INTO colour (name, hex) values ('D1D2DD', 'Mischka');
INSERT INTO colour (name, hex) values ('D1E231', 'Pear');
INSERT INTO colour (name, hex) values ('D2691E', 'Hot Cinnamon');
INSERT INTO colour (name, hex) values ('D27D46', 'Raw Sienna');
INSERT INTO colour (name, hex) values ('D29EAA', 'Careys Pink');
INSERT INTO colour (name, hex) values ('D2B48C', 'Tan');
INSERT INTO colour (name, hex) values ('D2DA97', 'Deco');
INSERT INTO colour (name, hex) values ('D2F6DE', 'Blue Romance');
INSERT INTO colour (name, hex) values ('D2F8B0', 'Gossip');
INSERT INTO colour (name, hex) values ('D3CBBA', 'Sisal');
INSERT INTO colour (name, hex) values ('D3CDC5', 'Swirl');
INSERT INTO colour (name, hex) values ('D47494', 'Charm');
INSERT INTO colour (name, hex) values ('D4B6AF', 'Clam Shell');
INSERT INTO colour (name, hex) values ('D4BF8D', 'Straw');
INSERT INTO colour (name, hex) values ('D4C4A8', 'Akaroa');
INSERT INTO colour (name, hex) values ('D4CD16', 'Bird Flower');
INSERT INTO colour (name, hex) values ('D4D7D9', 'Iron');
INSERT INTO colour (name, hex) values ('D4DFE2', 'Geyser');
INSERT INTO colour (name, hex) values ('D4E2FC', 'Hawkes Blue');
INSERT INTO colour (name, hex) values ('D54600', 'Grenadier');
INSERT INTO colour (name, hex) values ('D591A4', 'Can Can');
INSERT INTO colour (name, hex) values ('D59A6F', 'Whiskey');
INSERT INTO colour (name, hex) values ('D5D195', 'Winter Hazel');
INSERT INTO colour (name, hex) values ('D5F6E3', 'Granny Apple');
INSERT INTO colour (name, hex) values ('D69188', 'My Pink');
INSERT INTO colour (name, hex) values ('D6C562', 'Tacha');
INSERT INTO colour (name, hex) values ('D6CEF6', 'Moon Raker');
INSERT INTO colour (name, hex) values ('D6D6D1', 'Quill Gray');
INSERT INTO colour (name, hex) values ('D6FFDB', 'Snowy Mint');
INSERT INTO colour (name, hex) values ('D7837F', 'New York Pink');
INSERT INTO colour (name, hex) values ('D7C498', 'Pavlova');
INSERT INTO colour (name, hex) values ('D7D0FF', 'Fog');
INSERT INTO colour (name, hex) values ('D84437', 'Valencia');
INSERT INTO colour (name, hex) values ('D87C63', 'Japonica');
INSERT INTO colour (name, hex) values ('D8BFD8', 'Thistle');
INSERT INTO colour (name, hex) values ('D8C2D5', 'Maverick');
INSERT INTO colour (name, hex) values ('D8FCFA', 'Foam');
INSERT INTO colour (name, hex) values ('D94972', 'Cabaret');
INSERT INTO colour (name, hex) values ('D99376', 'Burning Sand');
INSERT INTO colour (name, hex) values ('D9B99B', 'Cameo');
INSERT INTO colour (name, hex) values ('D9D6CF', 'Timberwolf');
INSERT INTO colour (name, hex) values ('D9DCC1', 'Tana');
INSERT INTO colour (name, hex) values ('D9E4F5', 'Link Water');
INSERT INTO colour (name, hex) values ('D9F7FF', 'Mabel');
INSERT INTO colour (name, hex) values ('DA3287', 'Cerise');
INSERT INTO colour (name, hex) values ('DA5B38', 'Flame Pea');
INSERT INTO colour (name, hex) values ('DA6304', 'Bamboo');
INSERT INTO colour (name, hex) values ('DA6A41', 'Red Damask');
INSERT INTO colour (name, hex) values ('DA70D6', 'Orchid');
INSERT INTO colour (name, hex) values ('DA8A67', 'Copperfield');
INSERT INTO colour (name, hex) values ('DAA520', 'Golden Grass');
INSERT INTO colour (name, hex) values ('DAECD6', 'Zanah');
INSERT INTO colour (name, hex) values ('DAF4F0', 'Iceberg');
INSERT INTO colour (name, hex) values ('DAFAFF', 'Oyster Bay');
INSERT INTO colour (name, hex) values ('DB5079', 'Cranberry');
INSERT INTO colour (name, hex) values ('DB9690', 'Petite Orchid');
INSERT INTO colour (name, hex) values ('DB995E', 'Di Serria');
INSERT INTO colour (name, hex) values ('DBDBDB', 'Alto');
INSERT INTO colour (name, hex) values ('DBFFF8', 'Frosted Mint');
INSERT INTO colour (name, hex) values ('DC143C', 'Crimson');
INSERT INTO colour (name, hex) values ('DC4333', 'Punch');
INSERT INTO colour (name, hex) values ('DCB20C', 'Galliano');
INSERT INTO colour (name, hex) values ('DCB4BC', 'Blossom');
INSERT INTO colour (name, hex) values ('DCD747', 'Wattle');
INSERT INTO colour (name, hex) values ('DCD9D2', 'Westar');
INSERT INTO colour (name, hex) values ('DCDDCC', 'Moon Mist');
INSERT INTO colour (name, hex) values ('DCEDB4', 'Caper');
INSERT INTO colour (name, hex) values ('DCF0EA', 'Swans Down');
INSERT INTO colour (name, hex) values ('DDD6D5', 'Swiss Coffee');
INSERT INTO colour (name, hex) values ('DDF9F1', 'White Ice');
INSERT INTO colour (name, hex) values ('DE3163', 'Cerise Red');
INSERT INTO colour (name, hex) values ('DE6360', 'Roman');
INSERT INTO colour (name, hex) values ('DEA681', 'Tumbleweed');
INSERT INTO colour (name, hex) values ('DEBA13', 'Gold Tips');
INSERT INTO colour (name, hex) values ('DEC196', 'Brandy');
INSERT INTO colour (name, hex) values ('DECBC6', 'Wafer');
INSERT INTO colour (name, hex) values ('DED4A4', 'Sapling');
INSERT INTO colour (name, hex) values ('DED717', 'Barberry');
INSERT INTO colour (name, hex) values ('DEE5C0', 'Beryl Green');
INSERT INTO colour (name, hex) values ('DEF5FF', 'Pattens Blue');
INSERT INTO colour (name, hex) values ('DF73FF', 'Heliotrope');
INSERT INTO colour (name, hex) values ('DFBE6F', 'Apache');
INSERT INTO colour (name, hex) values ('DFCD6F', 'Chenin');
INSERT INTO colour (name, hex) values ('DFCFDB', 'Lola');
INSERT INTO colour (name, hex) values ('DFECDA', 'Willow Brook');
INSERT INTO colour (name, hex) values ('DFFF00', 'Chartreuse Yellow');
INSERT INTO colour (name, hex) values ('E0B0FF', 'Mauve');
INSERT INTO colour (name, hex) values ('E0B646', 'Anzac');
INSERT INTO colour (name, hex) values ('E0B974', 'Harvest Gold');
INSERT INTO colour (name, hex) values ('E0C095', 'Calico');
INSERT INTO colour (name, hex) values ('E0FFFF', 'Baby Blue');
INSERT INTO colour (name, hex) values ('E16865', 'Sunglo');
INSERT INTO colour (name, hex) values ('E1BC64', 'Equator');
INSERT INTO colour (name, hex) values ('E1C0C8', 'Pink Flare');
INSERT INTO colour (name, hex) values ('E1E6D6', 'Periglacial Blue');
INSERT INTO colour (name, hex) values ('E1EAD4', 'Kidnapper');
INSERT INTO colour (name, hex) values ('E1F6E8', 'Tara');
INSERT INTO colour (name, hex) values ('E25465', 'Mandy');
INSERT INTO colour (name, hex) values ('E2725B', 'Terracotta');
INSERT INTO colour (name, hex) values ('E28913', 'Golden Bell');
INSERT INTO colour (name, hex) values ('E292C0', 'Shocking');
INSERT INTO colour (name, hex) values ('E29418', 'Dixie');
INSERT INTO colour (name, hex) values ('E29CD2', 'Light Orchid');
INSERT INTO colour (name, hex) values ('E2D8ED', 'Snuff');
INSERT INTO colour (name, hex) values ('E2EBED', 'Mystic');
INSERT INTO colour (name, hex) values ('E2F3EC', 'Apple Green');
INSERT INTO colour (name, hex) values ('E30B5C', 'Razzmatazz');
INSERT INTO colour (name, hex) values ('E32636', 'Alizarin Crimson');
INSERT INTO colour (name, hex) values ('E34234', 'Cinnabar');
INSERT INTO colour (name, hex) values ('E3BEBE', 'Cavern Pink');
INSERT INTO colour (name, hex) values ('E3F5E1', 'Peppermint');
INSERT INTO colour (name, hex) values ('E3F988', 'Mindaro');
INSERT INTO colour (name, hex) values ('E47698', 'Deep Blush');
INSERT INTO colour (name, hex) values ('E49B0F', 'Gamboge');
INSERT INTO colour (name, hex) values ('E4C2D5', 'Melanie');
INSERT INTO colour (name, hex) values ('E4CFDE', 'Twilight');
INSERT INTO colour (name, hex) values ('E4D1C0', 'Bone');
INSERT INTO colour (name, hex) values ('E4D422', 'Sunflower');
INSERT INTO colour (name, hex) values ('E4D5B7', 'Grain Brown');
INSERT INTO colour (name, hex) values ('E4D69B', 'Zombie');
INSERT INTO colour (name, hex) values ('E4F6E7', 'Frostee');
INSERT INTO colour (name, hex) values ('E4FFD1', 'Snow Flurry');
INSERT INTO colour (name, hex) values ('E52B50', 'Amaranth');
INSERT INTO colour (name, hex) values ('E5841B', 'Zest');
INSERT INTO colour (name, hex) values ('E5CCC9', 'Dust Storm');
INSERT INTO colour (name, hex) values ('E5D7BD', 'Stark White');
INSERT INTO colour (name, hex) values ('E5D8AF', 'Hampton');
INSERT INTO colour (name, hex) values ('E5E0E1', 'Bon Jour');
INSERT INTO colour (name, hex) values ('E5E5E5', 'Mercury');
INSERT INTO colour (name, hex) values ('E5F9F6', 'Polar');
INSERT INTO colour (name, hex) values ('E64E03', 'Trinidad');
INSERT INTO colour (name, hex) values ('E6BE8A', 'Gold Sand');
INSERT INTO colour (name, hex) values ('E6BEA5', 'Cashmere');
INSERT INTO colour (name, hex) values ('E6D7B9', 'Double Spanish White');
INSERT INTO colour (name, hex) values ('E6E4D4', 'Satin Linen');
INSERT INTO colour (name, hex) values ('E6F2EA', 'Harp');
INSERT INTO colour (name, hex) values ('E6F8F3', 'Off Green');
INSERT INTO colour (name, hex) values ('E6FFE9', 'Hint of Green');
INSERT INTO colour (name, hex) values ('E6FFFF', 'Tranquil');
INSERT INTO colour (name, hex) values ('E77200', 'Mango Tango');
INSERT INTO colour (name, hex) values ('E7730A', 'Christine');
INSERT INTO colour (name, hex) values ('E79F8C', 'Tonys Pink');
INSERT INTO colour (name, hex) values ('E79FC4', 'Kobi');
INSERT INTO colour (name, hex) values ('E7BCB4', 'Rose Fog');
INSERT INTO colour (name, hex) values ('E7BF05', 'Corn');
INSERT INTO colour (name, hex) values ('E7CD8C', 'Putty');
INSERT INTO colour (name, hex) values ('E7ECE6', 'Gray Nurse');
INSERT INTO colour (name, hex) values ('E7F8FF', 'Lily White');
INSERT INTO colour (name, hex) values ('E7FEFF', 'Bubbles');
INSERT INTO colour (name, hex) values ('E89928', 'Fire Bush');
INSERT INTO colour (name, hex) values ('E8B9B3', 'Shilo');
INSERT INTO colour (name, hex) values ('E8E0D5', 'Pearl Bush');
INSERT INTO colour (name, hex) values ('E8EBE0', 'Green White');
INSERT INTO colour (name, hex) values ('E8F1D4', 'Chrome White');
INSERT INTO colour (name, hex) values ('E8F2EB', 'Gin');
INSERT INTO colour (name, hex) values ('E8F5F2', 'Aqua Squeeze');
INSERT INTO colour (name, hex) values ('E96E00', 'Clementine');
INSERT INTO colour (name, hex) values ('E97451', 'Burnt Sienna');
INSERT INTO colour (name, hex) values ('E97C07', 'Tahiti Gold');
INSERT INTO colour (name, hex) values ('E9CECD', 'Oyster Pink');
INSERT INTO colour (name, hex) values ('E9D75A', 'Confetti');
INSERT INTO colour (name, hex) values ('E9E3E3', 'Ebb');
INSERT INTO colour (name, hex) values ('E9F8ED', 'Ottoman');
INSERT INTO colour (name, hex) values ('E9FFFD', 'Clear Day');
INSERT INTO colour (name, hex) values ('EA88A8', 'Carissma');
INSERT INTO colour (name, hex) values ('EAAE69', 'Porsche');
INSERT INTO colour (name, hex) values ('EAB33B', 'Tulip Tree');
INSERT INTO colour (name, hex) values ('EAC674', 'Rob Roy');
INSERT INTO colour (name, hex) values ('EADAB8', 'Raffia');
INSERT INTO colour (name, hex) values ('EAE8D4', 'White Rock');
INSERT INTO colour (name, hex) values ('EAF6EE', 'Panache');
INSERT INTO colour (name, hex) values ('EAF6FF', 'Solitude');
INSERT INTO colour (name, hex) values ('EAF9F5', 'Aqua Spring');
INSERT INTO colour (name, hex) values ('EAFFFE', 'Dew');
INSERT INTO colour (name, hex) values ('EB9373', 'Apricot');
INSERT INTO colour (name, hex) values ('EBC2AF', 'Zinnwaldite');
INSERT INTO colour (name, hex) values ('ECA927', 'Fuel Yellow');
INSERT INTO colour (name, hex) values ('ECC54E', 'Ronchi');
INSERT INTO colour (name, hex) values ('ECC7EE', 'French Lilac');
INSERT INTO colour (name, hex) values ('ECCDB9', 'Just Right');
INSERT INTO colour (name, hex) values ('ECE090', 'Wild Rice');
INSERT INTO colour (name, hex) values ('ECEBBD', 'Fall Green');
INSERT INTO colour (name, hex) values ('ECEBCE', 'Aths Special');
INSERT INTO colour (name, hex) values ('ECF245', 'Starship');
INSERT INTO colour (name, hex) values ('ED0A3F', 'Red Ribbon');
INSERT INTO colour (name, hex) values ('ED7A1C', 'Tango');
INSERT INTO colour (name, hex) values ('ED9121', 'Carrot Orange');
INSERT INTO colour (name, hex) values ('ED989E', 'Sea Pink');
INSERT INTO colour (name, hex) values ('EDB381', 'Tacao');
INSERT INTO colour (name, hex) values ('EDC9AF', 'Desert Sand');
INSERT INTO colour (name, hex) values ('EDCDAB', 'Pancho');
INSERT INTO colour (name, hex) values ('EDDCB1', 'Chamois');
INSERT INTO colour (name, hex) values ('EDEA99', 'Primrose');
INSERT INTO colour (name, hex) values ('EDF5DD', 'Frost');
INSERT INTO colour (name, hex) values ('EDF5F5', 'Aqua Haze');
INSERT INTO colour (name, hex) values ('EDF6FF', 'Zumthor');
INSERT INTO colour (name, hex) values ('EDF9F1', 'Narvik');
INSERT INTO colour (name, hex) values ('EDFC84', 'Honeysuckle');
INSERT INTO colour (name, hex) values ('EE82EE', 'Lavender Magenta');
INSERT INTO colour (name, hex) values ('EEC1BE', 'Beauty Bush');
INSERT INTO colour (name, hex) values ('EED794', 'Chalky');
INSERT INTO colour (name, hex) values ('EED9C4', 'Almond');
INSERT INTO colour (name, hex) values ('EEDC82', 'Flax');
INSERT INTO colour (name, hex) values ('EEDEDA', 'Bizarre');
INSERT INTO colour (name, hex) values ('EEE3AD', 'Double Colonial White');
INSERT INTO colour (name, hex) values ('EEEEE8', 'Cararra');
INSERT INTO colour (name, hex) values ('EEEF78', 'Manz');
INSERT INTO colour (name, hex) values ('EEF0C8', 'Tahuna Sands');
INSERT INTO colour (name, hex) values ('EEF0F3', 'Athens Gray');
INSERT INTO colour (name, hex) values ('EEF3C3', 'Tusk');
INSERT INTO colour (name, hex) values ('EEF4DE', 'Loafer');
INSERT INTO colour (name, hex) values ('EEF6F7', 'Catskill White');
INSERT INTO colour (name, hex) values ('EEFDFF', 'Twilight Blue');
INSERT INTO colour (name, hex) values ('EEFF9A', 'Jonquil');
INSERT INTO colour (name, hex) values ('EEFFE2', 'Rice Flower');
INSERT INTO colour (name, hex) values ('EF863F', 'Jaffa');
INSERT INTO colour (name, hex) values ('EFEFEF', 'Gallery');
INSERT INTO colour (name, hex) values ('EFF2F3', 'Porcelain');
INSERT INTO colour (name, hex) values ('F091A9', 'Mauvelous');
INSERT INTO colour (name, hex) values ('F0D52D', 'Golden Dream');
INSERT INTO colour (name, hex) values ('F0DB7D', 'Golden Sand');
INSERT INTO colour (name, hex) values ('F0DC82', 'Buff');
INSERT INTO colour (name, hex) values ('F0E2EC', 'Prim');
INSERT INTO colour (name, hex) values ('F0E68C', 'Khaki');
INSERT INTO colour (name, hex) values ('F0EEFD', 'Selago');
INSERT INTO colour (name, hex) values ('F0EEFF', 'Titan White');
INSERT INTO colour (name, hex) values ('F0F8FF', 'Alice Blue');
INSERT INTO colour (name, hex) values ('F0FCEA', 'Feta');
INSERT INTO colour (name, hex) values ('F18200', 'Gold Drop');
INSERT INTO colour (name, hex) values ('F19BAB', 'Wewak');
INSERT INTO colour (name, hex) values ('F1E788', 'Sahara Sand');
INSERT INTO colour (name, hex) values ('F1E9D2', 'Parchment');
INSERT INTO colour (name, hex) values ('F1E9FF', 'Blue Chalk');
INSERT INTO colour (name, hex) values ('F1EEC1', 'Mint Julep');
INSERT INTO colour (name, hex) values ('F1F1F1', 'Seashell');
INSERT INTO colour (name, hex) values ('F1F7F2', 'Saltpan');
INSERT INTO colour (name, hex) values ('F1FFAD', 'Tidal');
INSERT INTO colour (name, hex) values ('F1FFC8', 'Chiffon');
INSERT INTO colour (name, hex) values ('F2552A', 'Flamingo');
INSERT INTO colour (name, hex) values ('F28500', 'Tangerine');
INSERT INTO colour (name, hex) values ('F2C3B2', 'Mandys Pink');
INSERT INTO colour (name, hex) values ('F2F2F2', 'Concrete');
INSERT INTO colour (name, hex) values ('F2FAFA', 'Black Squeeze');
INSERT INTO colour (name, hex) values ('F34723', 'Pomegranate');
INSERT INTO colour (name, hex) values ('F3AD16', 'Buttercup');
INSERT INTO colour (name, hex) values ('F3D69D', 'New Orleans');
INSERT INTO colour (name, hex) values ('F3D9DF', 'Vanilla Ice');
INSERT INTO colour (name, hex) values ('F3E7BB', 'Sidecar');
INSERT INTO colour (name, hex) values ('F3E9E5', 'Dawn Pink');
INSERT INTO colour (name, hex) values ('F3EDCF', 'Wheatfield');
INSERT INTO colour (name, hex) values ('F3FB62', 'Canary');
INSERT INTO colour (name, hex) values ('F3FBD4', 'Orinoco');
INSERT INTO colour (name, hex) values ('F3FFD8', 'Carla');
INSERT INTO colour (name, hex) values ('F400A1', 'Hollywood Cerise');
INSERT INTO colour (name, hex) values ('F4A460', 'Sandy brown');
INSERT INTO colour (name, hex) values ('F4C430', 'Saffron');
INSERT INTO colour (name, hex) values ('F4D81C', 'Ripe Lemon');
INSERT INTO colour (name, hex) values ('F4EBD3', 'Janna');
INSERT INTO colour (name, hex) values ('F4F2EE', 'Pampas');
INSERT INTO colour (name, hex) values ('F4F4F4', 'Wild Sand');
INSERT INTO colour (name, hex) values ('F4F8FF', 'Zircon');
INSERT INTO colour (name, hex) values ('F57584', 'Froly');
INSERT INTO colour (name, hex) values ('F5C85C', 'Cream Can');
INSERT INTO colour (name, hex) values ('F5C999', 'Manhattan');
INSERT INTO colour (name, hex) values ('F5D5A0', 'Maize');
INSERT INTO colour (name, hex) values ('F5DEB3', 'Wheat');
INSERT INTO colour (name, hex) values ('F5E7A2', 'Sandwisp');
INSERT INTO colour (name, hex) values ('F5E7E2', 'Pot Pourri');
INSERT INTO colour (name, hex) values ('F5E9D3', 'Albescent White');
INSERT INTO colour (name, hex) values ('F5EDEF', 'Soft Peach');
INSERT INTO colour (name, hex) values ('F5F3E5', 'Ecru White');
INSERT INTO colour (name, hex) values ('F5F5DC', 'Beige');
INSERT INTO colour (name, hex) values ('F5FB3D', 'Golden Fizz');
INSERT INTO colour (name, hex) values ('F5FFBE', 'Australian Mint');
INSERT INTO colour (name, hex) values ('F64A8A', 'French Rose');
INSERT INTO colour (name, hex) values ('F653A6', 'Brilliant Rose');
INSERT INTO colour (name, hex) values ('F6A4C9', 'Illusion');
INSERT INTO colour (name, hex) values ('F6F0E6', 'Merino');
INSERT INTO colour (name, hex) values ('F6F7F7', 'Black Haze');
INSERT INTO colour (name, hex) values ('F6FFDC', 'Spring Sun');
INSERT INTO colour (name, hex) values ('F7468A', 'Violet Red');
INSERT INTO colour (name, hex) values ('F77703', 'Chilean Fire');
INSERT INTO colour (name, hex) values ('F77FBE', 'Persian Pink');
INSERT INTO colour (name, hex) values ('F7B668', 'Rajah');
INSERT INTO colour (name, hex) values ('F7C8DA', 'Azalea');
INSERT INTO colour (name, hex) values ('F7DBE6', 'We Peep');
INSERT INTO colour (name, hex) values ('F7F2E1', 'Quarter Spanish White');
INSERT INTO colour (name, hex) values ('F7F5FA', 'Whisper');
INSERT INTO colour (name, hex) values ('F7FAF7', 'Snow Drift');
INSERT INTO colour (name, hex) values ('F8B853', 'Casablanca');
INSERT INTO colour (name, hex) values ('F8C3DF', 'Chantilly');
INSERT INTO colour (name, hex) values ('F8D9E9', 'Cherub');
INSERT INTO colour (name, hex) values ('F8DB9D', 'Marzipan');
INSERT INTO colour (name, hex) values ('F8DD5C', 'Energy Yellow');
INSERT INTO colour (name, hex) values ('F8E4BF', 'Givry');
INSERT INTO colour (name, hex) values ('F8F0E8', 'White Linen');
INSERT INTO colour (name, hex) values ('F8F4FF', 'Magnolia');
INSERT INTO colour (name, hex) values ('F8F6F1', 'Spring Wood');
INSERT INTO colour (name, hex) values ('F8F7DC', 'Coconut Cream');
INSERT INTO colour (name, hex) values ('F8F7FC', 'White Lilac');
INSERT INTO colour (name, hex) values ('F8F8F7', 'Desert Storm');
INSERT INTO colour (name, hex) values ('F8F99C', 'Texas');
INSERT INTO colour (name, hex) values ('F8FACD', 'Corn Field');
INSERT INTO colour (name, hex) values ('F8FDD3', 'Mimosa');
INSERT INTO colour (name, hex) values ('F95A61', 'Carnation');
INSERT INTO colour (name, hex) values ('F9BF58', 'Saffron Mango');
INSERT INTO colour (name, hex) values ('F9E0ED', 'Carousel Pink');
INSERT INTO colour (name, hex) values ('F9E4BC', 'Dairy Cream');
INSERT INTO colour (name, hex) values ('F9E663', 'Portica');
INSERT INTO colour (name, hex) values ('F9E6F4', 'Underage Pink');
INSERT INTO colour (name, hex) values ('F9EAF3', 'Amour');
INSERT INTO colour (name, hex) values ('F9F8E4', 'Rum Swizzle');
INSERT INTO colour (name, hex) values ('F9FF8B', 'Dolly');
INSERT INTO colour (name, hex) values ('F9FFF6', 'Sugar Cane');
INSERT INTO colour (name, hex) values ('FA7814', 'Ecstasy');
INSERT INTO colour (name, hex) values ('FA9D5A', 'Tan Hide');
INSERT INTO colour (name, hex) values ('FAD3A2', 'Corvette');
INSERT INTO colour (name, hex) values ('FADFAD', 'Peach Yellow');
INSERT INTO colour (name, hex) values ('FAE600', 'Turbo');
INSERT INTO colour (name, hex) values ('FAEAB9', 'Astra');
INSERT INTO colour (name, hex) values ('FAECCC', 'Champagne');
INSERT INTO colour (name, hex) values ('FAF0E6', 'Linen');
INSERT INTO colour (name, hex) values ('FAF3F0', 'Fantasy');
INSERT INTO colour (name, hex) values ('FAF7D6', 'Citrine White');
INSERT INTO colour (name, hex) values ('FAFAFA', 'Alabaster');
INSERT INTO colour (name, hex) values ('FAFDE4', 'Hint of Yellow');
INSERT INTO colour (name, hex) values ('FAFFA4', 'Milan');
INSERT INTO colour (name, hex) values ('FB607F', 'Brink Pink');
INSERT INTO colour (name, hex) values ('FB8989', 'Geraldine');
INSERT INTO colour (name, hex) values ('FBA0E3', 'Lavender Rose');
INSERT INTO colour (name, hex) values ('FBA129', 'Sea Buckthorn');
INSERT INTO colour (name, hex) values ('FBAC13', 'Sun');
INSERT INTO colour (name, hex) values ('FBAED2', 'Lavender Pink');
INSERT INTO colour (name, hex) values ('FBB2A3', 'Rose Bud');
INSERT INTO colour (name, hex) values ('FBBEDA', 'Cupid');
INSERT INTO colour (name, hex) values ('FBCCE7', 'Classic Rose');
INSERT INTO colour (name, hex) values ('FBCEB1', 'Apricot Peach');
INSERT INTO colour (name, hex) values ('FBE7B2', 'Banana Mania');
INSERT INTO colour (name, hex) values ('FBE870', 'Marigold Yellow');
INSERT INTO colour (name, hex) values ('FBE96C', 'Festival');
INSERT INTO colour (name, hex) values ('FBEA8C', 'Sweet Corn');
INSERT INTO colour (name, hex) values ('FBEC5D', 'Candy Corn');
INSERT INTO colour (name, hex) values ('FBF9F9', 'Hint of Red');
INSERT INTO colour (name, hex) values ('FBFFBA', 'Shalimar');
INSERT INTO colour (name, hex) values ('FC0FC0', 'Shocking Pink');
INSERT INTO colour (name, hex) values ('FC80A5', 'Tickle Me Pink');
INSERT INTO colour (name, hex) values ('FC9C1D', 'Tree Poppy');
INSERT INTO colour (name, hex) values ('FCC01E', 'Lightning Yellow');
INSERT INTO colour (name, hex) values ('FCD667', 'Goldenrod');
INSERT INTO colour (name, hex) values ('FCD917', 'Candlelight');
INSERT INTO colour (name, hex) values ('FCDA98', 'Cherokee');
INSERT INTO colour (name, hex) values ('FCF4D0', 'Double Pearl Lusta');
INSERT INTO colour (name, hex) values ('FCF4DC', 'Pearl Lusta');
INSERT INTO colour (name, hex) values ('FCF8F7', 'Vista White');
INSERT INTO colour (name, hex) values ('FCFBF3', 'Bianca');
INSERT INTO colour (name, hex) values ('FCFEDA', 'Moon Glow');
INSERT INTO colour (name, hex) values ('FCFFE7', 'China Ivory');
INSERT INTO colour (name, hex) values ('FCFFF9', 'Ceramic');
INSERT INTO colour (name, hex) values ('FD0E35', 'Torch Red');
INSERT INTO colour (name, hex) values ('FD5B78', 'Wild Watermelon');
INSERT INTO colour (name, hex) values ('FD7B33', 'Crusta');
INSERT INTO colour (name, hex) values ('FD7C07', 'Sorbus');
INSERT INTO colour (name, hex) values ('FD9FA2', 'Sweet Pink');
INSERT INTO colour (name, hex) values ('FDD5B1', 'Light Apricot');
INSERT INTO colour (name, hex) values ('FDD7E4', 'Pig Pink');
INSERT INTO colour (name, hex) values ('FDE1DC', 'Cinderella');
INSERT INTO colour (name, hex) values ('FDE295', 'Golden Glow');
INSERT INTO colour (name, hex) values ('FDE910', 'Lemon');
INSERT INTO colour (name, hex) values ('FDF5E6', 'Old Lace');
INSERT INTO colour (name, hex) values ('FDF6D3', 'Half Colonial White');
INSERT INTO colour (name, hex) values ('FDF7AD', 'Drover');
INSERT INTO colour (name, hex) values ('FDFEB8', 'Pale Prim');
INSERT INTO colour (name, hex) values ('FDFFD5', 'Cumulus');
INSERT INTO colour (name, hex) values ('FE28A2', 'Persian Rose');
INSERT INTO colour (name, hex) values ('FE4C40', 'Sunset Orange');
INSERT INTO colour (name, hex) values ('FE6F5E', 'Bittersweet');
INSERT INTO colour (name, hex) values ('FE9D04', 'California');
INSERT INTO colour (name, hex) values ('FEA904', 'Yellow Sea');
INSERT INTO colour (name, hex) values ('FEBAAD', 'Melon');
INSERT INTO colour (name, hex) values ('FED33C', 'Bright Sun');
INSERT INTO colour (name, hex) values ('FED85D', 'Dandelion');
INSERT INTO colour (name, hex) values ('FEDB8D', 'Salomie');
INSERT INTO colour (name, hex) values ('FEE5AC', 'Cape Honey');
INSERT INTO colour (name, hex) values ('FEEBF3', 'Remy');
INSERT INTO colour (name, hex) values ('FEEFCE', 'Oasis');
INSERT INTO colour (name, hex) values ('FEF0EC', 'Bridesmaid');
INSERT INTO colour (name, hex) values ('FEF2C7', 'Beeswax');
INSERT INTO colour (name, hex) values ('FEF3D8', 'Bleach White');
INSERT INTO colour (name, hex) values ('FEF4CC', 'Pipi');
INSERT INTO colour (name, hex) values ('FEF4DB', 'Half Spanish White');
INSERT INTO colour (name, hex) values ('FEF4F8', 'Wisp Pink');
INSERT INTO colour (name, hex) values ('FEF5F1', 'Provincial Pink');
INSERT INTO colour (name, hex) values ('FEF7DE', 'Half Dutch White');
INSERT INTO colour (name, hex) values ('FEF8E2', 'Solitaire');
INSERT INTO colour (name, hex) values ('FEF8FF', 'White Pointer');
INSERT INTO colour (name, hex) values ('FEF9E3', 'Off Yellow');
INSERT INTO colour (name, hex) values ('FEFCED', 'Orange White');
INSERT INTO colour (name, hex) values ('FF0000', 'Red');
INSERT INTO colour (name, hex) values ('FF007F', 'Rose');
INSERT INTO colour (name, hex) values ('FF00CC', 'Purple Pizzazz');
INSERT INTO colour (name, hex) values ('FF00FF', 'Magenta / Fuchsia');
INSERT INTO colour (name, hex) values ('FF2400', 'Scarlet');
INSERT INTO colour (name, hex) values ('FF3399', 'Wild Strawberry');
INSERT INTO colour (name, hex) values ('FF33CC', 'Razzle Dazzle Rose');
INSERT INTO colour (name, hex) values ('FF355E', 'Radical Red');
INSERT INTO colour (name, hex) values ('FF3F34', 'Red Orange');
INSERT INTO colour (name, hex) values ('FF4040', 'Coral Red');
INSERT INTO colour (name, hex) values ('FF4D00', 'Vermilion');
INSERT INTO colour (name, hex) values ('FF4F00', 'International Orange');
INSERT INTO colour (name, hex) values ('FF6037', 'Outrageous Orange');
INSERT INTO colour (name, hex) values ('FF6600', 'Blaze Orange');
INSERT INTO colour (name, hex) values ('FF66FF', 'Pink Flamingo');
INSERT INTO colour (name, hex) values ('FF681F', 'Orange');
INSERT INTO colour (name, hex) values ('FF69B4', 'Hot Pink');
INSERT INTO colour (name, hex) values ('FF6B53', 'Persimmon');
INSERT INTO colour (name, hex) values ('FF6FFF', 'Blush Pink');
INSERT INTO colour (name, hex) values ('FF7034', 'Burning Orange');
INSERT INTO colour (name, hex) values ('FF7518', 'Pumpkin');
INSERT INTO colour (name, hex) values ('FF7D07', 'Flamenco');
INSERT INTO colour (name, hex) values ('FF7F00', 'Flush Orange');
INSERT INTO colour (name, hex) values ('FF7F50', 'Coral');
INSERT INTO colour (name, hex) values ('FF8C69', 'Salmon');
INSERT INTO colour (name, hex) values ('FF9000', 'Pizazz');
INSERT INTO colour (name, hex) values ('FF910F', 'West Side');
INSERT INTO colour (name, hex) values ('FF91A4', 'Pink Salmon');
INSERT INTO colour (name, hex) values ('FF9933', 'Neon Carrot');
INSERT INTO colour (name, hex) values ('FF9966', 'Atomic Tangerine');
INSERT INTO colour (name, hex) values ('FF9980', 'Vivid Tangerine');
INSERT INTO colour (name, hex) values ('FF9E2C', 'Sunshade');
INSERT INTO colour (name, hex) values ('FFA000', 'Orange Peel');
INSERT INTO colour (name, hex) values ('FFA194', 'Mona Lisa');
INSERT INTO colour (name, hex) values ('FFA500', 'Web Orange');
INSERT INTO colour (name, hex) values ('FFA6C9', 'Carnation Pink');
INSERT INTO colour (name, hex) values ('FFAB81', 'Hit Pink');
INSERT INTO colour (name, hex) values ('FFAE42', 'Yellow Orange');
INSERT INTO colour (name, hex) values ('FFB0AC', 'Cornflower Lilac');
INSERT INTO colour (name, hex) values ('FFB1B3', 'Sundown');
INSERT INTO colour (name, hex) values ('FFB31F', 'My Sin');
INSERT INTO colour (name, hex) values ('FFB555', 'Texas Rose');
INSERT INTO colour (name, hex) values ('FFB7D5', 'Cotton Candy');
INSERT INTO colour (name, hex) values ('FFB97B', 'Macaroni and Cheese');
INSERT INTO colour (name, hex) values ('FFBA00', 'Selective Yellow');
INSERT INTO colour (name, hex) values ('FFBD5F', 'Koromiko');
INSERT INTO colour (name, hex) values ('FFBF00', 'Amber');
INSERT INTO colour (name, hex) values ('FFC0A8', 'Wax Flower');
INSERT INTO colour (name, hex) values ('FFC0CB', 'Pink');
INSERT INTO colour (name, hex) values ('FFC3C0', 'Your Pink');
INSERT INTO colour (name, hex) values ('FFC901', 'Supernova');
INSERT INTO colour (name, hex) values ('FFCBA4', 'Flesh');
INSERT INTO colour (name, hex) values ('FFCC33', 'Sunglow');
INSERT INTO colour (name, hex) values ('FFCC5C', 'Golden Tainoi');
INSERT INTO colour (name, hex) values ('FFCC99', 'Peach Orange');
INSERT INTO colour (name, hex) values ('FFCD8C', 'Chardonnay');
INSERT INTO colour (name, hex) values ('FFD1DC', 'Pastel Pink');
INSERT INTO colour (name, hex) values ('FFD2B7', 'Romantic');
INSERT INTO colour (name, hex) values ('FFD38C', 'Grandis');
INSERT INTO colour (name, hex) values ('FFD700', 'Gold');
INSERT INTO colour (name, hex) values ('FFD800', 'School bus Yellow');
INSERT INTO colour (name, hex) values ('FFD8D9', 'Cosmos');
INSERT INTO colour (name, hex) values ('FFDB58', 'Mustard');
INSERT INTO colour (name, hex) values ('FFDCD6', 'Peach Schnapps');
INSERT INTO colour (name, hex) values ('FFDDAF', 'Caramel');
INSERT INTO colour (name, hex) values ('FFDDCD', 'Tuft Bush');
INSERT INTO colour (name, hex) values ('FFDDCF', 'Watusi');
INSERT INTO colour (name, hex) values ('FFDDF4', 'Pink Lace');
INSERT INTO colour (name, hex) values ('FFDEAD', 'Navajo White');
INSERT INTO colour (name, hex) values ('FFDEB3', 'Frangipani');
INSERT INTO colour (name, hex) values ('FFE1DF', 'Pippin');
INSERT INTO colour (name, hex) values ('FFE1F2', 'Pale Rose');
INSERT INTO colour (name, hex) values ('FFE2C5', 'Negroni');
INSERT INTO colour (name, hex) values ('FFE5A0', 'Cream Brulee');
INSERT INTO colour (name, hex) values ('FFE5B4', 'Peach');
INSERT INTO colour (name, hex) values ('FFE6C7', 'Tequila');
INSERT INTO colour (name, hex) values ('FFE772', 'Kournikova');
INSERT INTO colour (name, hex) values ('FFEAC8', 'Sandy Beach');
INSERT INTO colour (name, hex) values ('FFEAD4', 'Karry');
INSERT INTO colour (name, hex) values ('FFEC13', 'Broom');
INSERT INTO colour (name, hex) values ('FFEDBC', 'Colonial White');
INSERT INTO colour (name, hex) values ('FFEED8', 'Derby');
INSERT INTO colour (name, hex) values ('FFEFA1', 'Vis Vis');
INSERT INTO colour (name, hex) values ('FFEFC1', 'Egg White');
INSERT INTO colour (name, hex) values ('FFEFD5', 'Papaya Whip');
INSERT INTO colour (name, hex) values ('FFEFEC', 'Fair Pink');
INSERT INTO colour (name, hex) values ('FFF0DB', 'Peach Cream');
INSERT INTO colour (name, hex) values ('FFF0F5', 'Lavender blush');
INSERT INTO colour (name, hex) values ('FFF14F', 'Gorse');
INSERT INTO colour (name, hex) values ('FFF1B5', 'Buttermilk');
INSERT INTO colour (name, hex) values ('FFF1D8', 'Pink Lady');
INSERT INTO colour (name, hex) values ('FFF1EE', 'Forget Me Not');
INSERT INTO colour (name, hex) values ('FFF1F9', 'Tutu');
INSERT INTO colour (name, hex) values ('FFF39D', 'Picasso');
INSERT INTO colour (name, hex) values ('FFF3F1', 'Chardon');
INSERT INTO colour (name, hex) values ('FFF46E', 'Paris Daisy');
INSERT INTO colour (name, hex) values ('FFF4CE', 'Barley White');
INSERT INTO colour (name, hex) values ('FFF4DD', 'Egg Sour');
INSERT INTO colour (name, hex) values ('FFF4E0', 'Sazerac');
INSERT INTO colour (name, hex) values ('FFF4E8', 'Serenade');
INSERT INTO colour (name, hex) values ('FFF4F3', 'Chablis');
INSERT INTO colour (name, hex) values ('FFF5EE', 'Seashell Peach');
INSERT INTO colour (name, hex) values ('FFF5F3', 'Sauvignon');
INSERT INTO colour (name, hex) values ('FFF6D4', 'Milk Punch');
INSERT INTO colour (name, hex) values ('FFF6DF', 'Varden');
INSERT INTO colour (name, hex) values ('FFF6F5', 'Rose White');
INSERT INTO colour (name, hex) values ('FFF8D1', 'Baja White');
INSERT INTO colour (name, hex) values ('FFF9E2', 'Gin Fizz');
INSERT INTO colour (name, hex) values ('FFF9E6', 'Early Dawn');
INSERT INTO colour (name, hex) values ('FFFACD', 'Lemon Chiffon');
INSERT INTO colour (name, hex) values ('FFFAF4', 'Bridal Heath');
INSERT INTO colour (name, hex) values ('FFFBDC', 'Scotch Mist');
INSERT INTO colour (name, hex) values ('FFFBF9', 'Soapstone');
INSERT INTO colour (name, hex) values ('FFFC99', 'Witch Haze');
INSERT INTO colour (name, hex) values ('FFFCEA', 'Buttery White');
INSERT INTO colour (name, hex) values ('FFFCEE', 'Island Spice');
INSERT INTO colour (name, hex) values ('FFFDD0', 'Cream');
INSERT INTO colour (name, hex) values ('FFFDE6', 'Chilean Heath');
INSERT INTO colour (name, hex) values ('FFFDE8', 'Travertine');
INSERT INTO colour (name, hex) values ('FFFDF3', 'Orchid White');
INSERT INTO colour (name, hex) values ('FFFDF4', 'Quarter Pearl Lusta');
INSERT INTO colour (name, hex) values ('FFFEE1', 'Half and Half');
INSERT INTO colour (name, hex) values ('FFFEEC', 'Apricot White');
INSERT INTO colour (name, hex) values ('FFFEF0', 'Rice Cake');
INSERT INTO colour (name, hex) values ('FFFEF6', 'Black White');
INSERT INTO colour (name, hex) values ('FFFEFD', 'Romance');
INSERT INTO colour (name, hex) values ('FFFF00', 'Yellow');
INSERT INTO colour (name, hex) values ('FFFF66', 'Laser Lemon');
INSERT INTO colour (name, hex) values ('FFFF99', 'Pale Canary');
INSERT INTO colour (name, hex) values ('FFFFB4', 'Portafino');
INSERT INTO colour (name, hex) values ('FFFFF0', 'Ivory');
INSERT INTO colour (name, hex) values ('FFFFFF', 'White')

# --- !Downs
TRUNCATE TABLE colour;